#import "template.typ": * // import everything from template file
#show: template // show everything rule (i.e. the entire document)
#show: appendix("S", 1)

= #ruby[仮名][か|な]

== 平仮名（ひらがな）

Some general notes:
- The ん character is rarely used by itself, but suffixed to another character to add the "n" sound.

=== Mnemonics

// @typstyle off
#general_table(
  [平仮名 mnemonic table. #super[#sym.dagger]Particle romanisations.], // caption
  "tbl:hiragana-mnemonics",  // label
  5,  // column_sizes
  (center, center, center, center, left),  // column_aligns
  scale_factor: 1,
  hline,
  table.header[#rc(1, 2)[*平仮名*]][{*Hepburn*#lb()*romanisation*}][{*Keyboard*#lb()*command*}][*Mnemonic*],
  hline,
  [あ], [#sansj[あ]], [a], [`a`], ["A" shape],
  [い], [#sansj[い]], [i], [`i`], [#underline[ee]l],
  [う], [#sansj[う]], [u], [`u`], ["u" shape],
  [え], [#sansj[え]], [e], [`e`], [#underline[e]xotic swan],
  [お], [#sansj[お]], [o], [`o`], [double "o" shape],
  [か], [#sansj[か]], [ka], [`ka`], [咖啡],
  [が], [#sansj[が]], [ga], [`ga`], [],
  [き], [#sansj[き]], [ki], [`ki`], [#underline[ke]y],
  [きゃ], [#sansj[きゃ]], [kya], [`kya`], [],
  [きゅ], [#sansj[きゅ]], [kyu], [`kyu`], [],
  [きょ], [#sansj[きょ]], [kyo], [`kyo`], [],
  [ぎ], [#sansj[ぎ]], [gi], [`gi`], [],
  [ぎゃ], [#sansj[ぎゃ]], [gya], [`gya`], [],
  [ぎゅ], [#sansj[ぎゅ]], [gyu], [`gyu`], [],
  [ぎょ], [#sansj[ぎょ]], [gyo], [`gyo`], [],
  [く], [#sansj[く]], [ku], [`ku`], [bird #underline[ku]-ku],
  [ぐ], [#sansj[ぐ]], [gu], [`gu`], [],
  [け], [#sansj[け]], [ke], [`ke`], [#underline[ke]lp (loose kelp)],
  [げ], [#sansj[げ]], [ge], [`ge`], [],
  [こ], [#sansj[こ]], [ko], [`ko`], [#underline[co]-habiting worms],
  [ご], [#sansj[ご]], [go], [`go`], [],
  [さ], [#sansj[さ]], [sa], [`sa`], [#underline[sa]lsa (two hand stir) / NOT "5"],
  [ざ], [#sansj[ざ]], [za], [`za`], [],
  [し], [#sansj[し]], [shi], [#textlightgrey[`si`/]`shi`], [#underline[shee]p; shepherd's crook],
  [しゃ], [#sansj[しゃ]], [sha], [`sha`], [],
  [しゅ], [#sansj[しゅ]], [shu], [`shu`], [],
  [しょ], [#sansj[しょ]], [sho], [`sho`], [],
  [じ], [#sansj[じ]], [ji], [#textlightgrey[`zi`/]`ji`], [],
  [じゃ], [#sansj[じゃ]], [ja], [#textlightgrey[`jya`/]`ja`], [],
  [じゅ], [#sansj[じゅ]], [ju], [#textlightgrey[`jyu`/]`ju`], [],
  [じょ], [#sansj[じょ]], [jo], [#textlightgrey[`jyo`/]`jo`], [],
  [す], [#sansj[す]], [su], [`su`], [#underline[sw]ing],
  [ず], [#sansj[ず]], [zu], [`zu`], [],
  [せ], [#sansj[せ]], [se], [`se`], [#ruby[世界][せ|かい]],
  [ぜ], [#sansj[ぜ]], [ze], [`ze`], [],
  [そ], [#sansj[そ]], [so], [`so`], [#underline[so]da / "sword" shape],
  [ぞ], [#sansj[ぞ]], [zo], [`zo`], [],
  [た], [#sansj[た]], [ta], [`ta`], ["ta" shape],
  [だ], [#sansj[だ]], [da], [`da`], [],
  [ち], [#sansj[ち]], [chi], [#textlightgrey[`ti`/]`chi`], [the "5"],
  [ちゃ], [#sansj[ちゃ]], [cha], [`cha`], [],
  [ちゅ], [#sansj[ちゅ]], [chu], [`chu`], [],
  [ちょ], [#sansj[ちょ]], [cho], [`cho`], [],
  [ぢ], [#sansj[ぢ]], [ji], [#textred[`di`]], [],
  [ぢゃ], [#sansj[ぢゃ]], [ja], [#textred[`dya`]], [],
  [ぢゅ], [#sansj[ぢゅ]], [ju], [#textred[`dyu`]], [],
  [ぢょ], [#sansj[ぢょ]], [jo], [#textred[`dyo`]], [],
  [つ], [#sansj[つ]], [tsu], [#textlightgrey[`tu`/]`tsu`], [#underline[tsu]nami],
  [づ], [#sansj[づ]], [zu], [#textred[`du`]], [],
  [て], [#sansj[て]], [te], [`te`], [#underline[te]lescope],
  [で], [#sansj[で]], [de], [`de`], [],
  [と], [#sansj[と]], [to], [`to`], [#underline[to]e with splinter],
  [ど], [#sansj[ど]], [do], [`do`], [],
  [な], [#sansj[な]], [na], [`na`], [#underline[nu]n praying to cross],
  [に], [#sansj[に]], [ni], [`ni`], [#underline[nee]dle],
  [にゃ], [#sansj[にゃ]], [nya], [`nya`], [],
  [にゅ], [#sansj[にゅ]], [nyu], [`nyu`], [],
  [にょ], [#sansj[にょ]], [nyo], [`nyo`], [],
  [ぬ], [#sansj[ぬ]], [nu], [`nu`], [#underline[noo]dles *with tail*],
  [ね], [#sansj[ね]], [ne], [`ne`], [ねこ (#underline[ne]ko) *with tail*],
  [の], [#sansj[の]], [no], [`no`], [pig #underline[no]se],
  [は], [#sansj[は]], [ha/wa#super[#sym.dagger]], [#textred[`ha`]], ["Ha" shape],
  [ば], [#sansj[ば]], [ba], [`ba`], [],
  [ぱ], [#sansj[ぱ]], [pa], [`pa`], [],
  [ひ], [#sansj[ひ]], [hi], [`hi`], [#underline[hee]l / #underline[he] has a big nose],
  [ひゃ], [#sansj[ひゃ]], [hya], [`hya`], [],
  [ひゅ], [#sansj[ひゅ]], [hyu], [`hyu`], [],
  [ひょ], [#sansj[ひょ]], [hyo], [`hyo`], [],
  [び], [#sansj[び]], [bi], [`bi`], [],
  [びゃ], [#sansj[びゃ]], [bya], [`bya`], [],
  [びゅ], [#sansj[びゅ]], [byu], [`byu`], [],
  [びょ], [#sansj[びょ]], [byo], [`byo`], [],
  [ぴ], [#sansj[ぴ]], [pi], [`pi`], [],
  [ぴゃ], [#sansj[ぴゃ]], [pya], [`pya`], [],
  [ぴゅ], [#sansj[ぴゅ]], [pyu], [`pyu`], [],
  [ぴょ], [#sansj[ぴょ]], [pyo], [`pyo`], [],
  [ふ], [#sansj[ふ]], [fu], [#textlightgrey[`hu`/]`fu`], [Mount #underline[Fu]ji],
  [ぶ], [#sansj[ぶ]], [bu], [`bu`], [],
  [ぷ], [#sansj[ぷ]], [pu], [`pu`], [],
  [へ], [#sansj[へ]], [he/e#super[#sym.dagger]], [#textred[`he`]], [#underline[he]adband / Mount St. #underline[He]lens],
  [べ], [#sansj[べ]], [be], [`be`], [],
  [ぺ], [#sansj[ぺ]], [pe], [`pe`], [],
  [ほ], [#sansj[ほ]], [ho], [`ho`], [mutated santa says #underline[ho] ho ho],
  [ぼ], [#sansj[ぼ]], [bo], [`bo`], [],
  [ぽ], [#sansj[ぽ]], [po], [`po`], [],
  [ま], [#sansj[ま]], [ma], [`ma`], [mutated mom with snake tail],
  [み], [#sansj[み]], [mi], [`mi`], [#underline[me] just turned 21],
  [みゃ], [#sansj[みゃ]], [mya], [`mya`], [],
  [みゅ], [#sansj[みゅ]], [myu], [`myu`], [],
  [みょ], [#sansj[みょ]], [myo], [`myo`], [],
  [む], [#sansj[む]], [mu], [`mu`], [cow says #underline[moo]],
  [め], [#sansj[め]], [me], [`me`], [eye shape *without tail*],
  [も], [#sansj[も]], [mo], [`mo`], [#underline[mo]re worms to catch #underline[mo]re fish],
  [や], [#sansj[や]], [ya], [`ya`], [#underline[ya]cht with anchor down],
  [ゆ], [#sansj[ゆ]], [yu], [`yu`], [#underline[u]-tensils],
  [よ], [#sansj[よ]], [yo], [`yo`], ["yo" shape],
  [ら], [#sansj[ら]], [ra], [`ra`], [#underline[ra]bbit],
  [り], [#sansj[り]], [ri], [`ri`], [reeds],
  [りゃ], [#sansj[りゃ]], [rya], [`rya`], [],
  [りゅ], [#sansj[りゅ]], [ryu], [`ryu`], [],
  [りょ], [#sansj[りょ]], [ryo], [`ryo`], [],
  [る], [#sansj[る]], [ru], [`ru`], [weird #underline[rou]te *with tail*],
  [れ], [#sansj[れ]], [re], [`re`], [#underline[re]tching guy kneeled down],
  [ろ], [#sansj[ろ]], [ro], [`ro`], [normal #underline[ro]ad *without tail*],
  [わ], [#sansj[わ]], [wa], [`wa`], [#underline[wa]llaby / #underline[wa]sp],
  [を], [#sansj[を]], [wo/o#super[#sym.dagger]], [`wo`], [#underline[wo]ah the water is cold],
  [ん], [#sansj[ん]], [nn], [#textred[`nn`]], ["n" shape],
  [ぁ], [#sansj[ぁ]], [?], [#textlightgrey[`la`/]#textred[`xa`]], [],
  [ぃ], [#sansj[ぃ]], [?], [#textlightgrey[`li`/]#textred[`xi`]], [],
  [ぅ], [#sansj[ぅ]], [?], [#textlightgrey[`lu`/]#textred[`xu`]], [],
  [ぇ], [#sansj[ぇ]], [?], [#textlightgrey[`le`/]#textred[`xe`]], [],
  [ぉ], [#sansj[ぉ]], [?], [#textlightgrey[`lo`/]#textred[`xo`]], [],
  [ゃ], [#sansj[ゃ]], [?], [#textlightgrey[`lya`/]#textred[`xya`]], [],
  [ゅ], [#sansj[ゅ]], [?], [#textlightgrey[`lyu`/]#textred[`xyu`]], [],
  [ょ], [#sansj[ょ]], [?], [#textlightgrey[`lyo`/]#textred[`xyo`]], [],
  [っ], [#sansj[っ]], [#super[`+1`]`>`], [#textlightgrey[`ltu`/`ltsu`/#textred[`xtsu`]/]repeat `>`], [],
  hline,
)


== 片仮名（カタカナ）

Some general notes:
- Usage of the ・ symbol to denote word boundaries is completely optional.


=== Mnemonics

// @typstyle off
#general_table(
  [片仮名 mnemonic table. Some entries were taken from #link("https://en.wikipedia.org/wiki/Hepburn_romanization\#Extended_katakana")[Wikipedia (Hepburn Romanisation)] but only the orange and blue ones are taken, since the beige and purple ones are regarded as unofficial (by me).], // caption
  "tbl:katakana-mnemonics",  // label
  5,  // column_sizes
  (center, center, center, center, left),  // column_aligns
  scale_factor: 1,
  hline,
  table.header[#rc(1, 2)[*片仮名*]][*Hepburn*#lb()*romanisation*][*Keyboard*#lb()*command*][*Mnemonic*],
  hline,
  [ア], [#sansj[ア]], [a], [`a`], ["A" shape],
  [イ], [#sansj[イ]], [i], [`i`], [#underline[e]agle perched],
  [#textblue[イェ]], [#textblue[#sansj[イェ]]], [#textblue[ye]], [#textblue[`ye`]], [],
  [ウ], [#sansj[ウ]], [u], [`u`], [same shape as う],
  [#textblue[ウィ]], [#textblue[#sansj[ウィ]]], [#textblue[wi]], [#textblue[`wi`]], [],
  [#textblue[ウェ]], [#textblue[#sansj[ウェ]]], [#textblue[we]], [#textblue[`we`]], [],
  [#textblue[ウォ]], [#textblue[#sansj[ウォ]]], [#textblue[wo]], [#textred[`uxo`]], [],
  // [],
  [#textblue[ヴ]], [#textblue[#sansj[ヴ]]], [#textblue[vu]], [#textblue[`vu`]], [],
  [#textblue[ヴァ]], [#textblue[#sansj[ヴァ]]], [#textblue[va]], [#textblue[`va`]], [],
  [#textblue[ヴィ]], [#textblue[#sansj[ヴィ]]], [#textblue[vi]], [#textblue[`vi`]], [],
  [#textblue[ヴュ]], [#textblue[#sansj[ヴュ]]], [#textblue[vyu]], [#textblue[`vyu`]], [],
  [#textblue[ヴェ]], [#textblue[#sansj[ヴェ]]], [#textblue[ve]], [#textblue[`ve`]], [],
  [#textblue[ヴォ]], [#textblue[#sansj[ヴォ]]], [#textblue[vo]], [#textblue[`vo`]], [],
  [エ], [#sansj[エ]], [e], [`e`], [#underline[e]ngineer bar],
  [オ], [#sansj[オ]], [o], [`o`], [#underline[o]pera talent (才) singing],
  [カ], [#sansj[カ]], [ka], [`ka`], [same shape as か],
  [ガ], [#sansj[ガ]], [ga], [`ga`], [],
  [キ], [#sansj[キ]], [ki], [`ki`], [same shape as き],
  [キャ], [#sansj[キャ]], [kya], [`kya`], [],
  [キュ], [#sansj[キュ]], [kyu], [`kyu`], [],
  [キョ], [#sansj[キョ]], [kyo], [`kyo`], [],
  [ギ], [#sansj[ギ]], [gi], [`gi`], [],
  [ギャ], [#sansj[ギャ]], [gya], [`gya`], [],
  [ギュ], [#sansj[ギュ]], [gyu], [`gyu`], [],
  [ギョ], [#sansj[ギョ]], [gyo], [`gyo`], [],
  [ク], [#sansj[ク]], [ku], [`ku`], [#underline[coo]k's hat],
  [#textblue[クァ]], [#textblue[#sansj[クァ]]], [#textblue[kwa]], [#textblue[`kwa`]], [],
  [#textblue[クィ]], [#textblue[#sansj[クィ]]], [#textblue[kwi]], [#textblue[`kwi`]], [],
  [#textblue[クェ]], [#textblue[#sansj[クェ]]], [#textblue[kwe]], [#textblue[`kwe`]], [],
  [#textblue[クォ]], [#textblue[#sansj[クォ]]], [#textblue[kwo]], [#textblue[`kwo`]], [],
  [グ], [#sansj[グ]], [gu], [`gu`], [],
  [#textblue[グァ]], [#textblue[#sansj[グァ]]], [#textblue[gwa]], [#textblue[`gwa`]], [],
  [ケ], [#sansj[ケ]], [ke], [`ke`], ["k" shape],
  [ゲ], [#sansj[ゲ]], [ge], [`ge`], [],
  [コ], [#sansj[コ]], [ko], [`ko`], [broken 口 (CN) / two #underline[co]rners],
  [ゴ], [#sansj[ゴ]], [go], [`go`], [],
  [サ], [#sansj[サ]], [sa], [`sa`], [#underline[sa]rdines and #underline[sa]lmon (bigger)],
  [ザ], [#sansj[ザ]], [za], [`za`], [],
  [シ], [#sansj[シ]], [shi], [#textlightgrey[`si`/]`shi`], [same direction as し],
  [シャ], [#sansj[シャ]], [sha], [`sha`], [],
  [シュ], [#sansj[シュ]], [shu], [`shu`], [],
  [#textblue[シェ]], [#textblue[#sansj[シュ]]], [#textblue[she]], [#textblue[`she`]], [],
  [ショ], [#sansj[ショ]], [sho], [`sho`], [],
  [ジ], [#sansj[ジ]], [ji], [#textlightgrey[`zi`/]`ji`], [],
  [ジャ], [#sansj[ジャ]], [ja], [#textlightgrey[`jya`/]`ja`], [],
  [ジュ], [#sansj[ジュ]], [ju], [#textlightgrey[`jyu`/]`ju`], [],
  [#textblue[ジェ]], [#textblue[#sansj[ジェ]]], [#textblue[je]], [#textblue[#textlightgrey[`jye`/]`je`]], [],
  [ジョ], [#sansj[ジョ]], [jo], [#textlightgrey[`jyo`/]`jo`], [],
  [ス], [#sansj[ス]], [su], [`su`], [#underline[su]perman],
  // [], [], [], [], [],
  [ズ], [#sansj[ズ]], [zu], [`zu`], [],
  // [], [], [], [], [],
  [セ], [#sansj[セ]], [se], [`se`], [same shape as せ],
  [ゼ], [#sansj[ゼ]], [ze], [`ze`], [],
  [ソ], [#sansj[ソ]], [so], [`so`], [#underline[se]wing needles],
  [ゾ], [#sansj[ゾ]], [zo], [`zo`], [],
  [タ], [#sansj[タ]], [ta], [`ta`], [#underline[ti]dal wave],
  [ダ], [#sansj[ダ]], [da], [`da`], [],
  [チ], [#sansj[チ]], [chi], [#textlightgrey[`ti`/]`chi`], [#underline[chee]r / #ruby[千][ち]],
  [チャ], [#sansj[チャ]], [cha], [`cha`], [],
  [チュ], [#sansj[チュ]], [chu], [`chu`], [],
  [#textblue[チェ]], [#textblue[#sansj[チェ]]], [#textblue[che]], [#textblue[`che`]], [],
  [チョ], [#sansj[チョ]], [cho], [`cho`], [],
  [ヂ], [#sansj[ヂ]], [ji], [#textred[`di`]], [],
  [ヂャ], [#sansj[ヂャ]], [ja], [#textred[`dya`]], [],
  [ヂュ], [#sansj[ヂュ]], [ju], [#textred[`dyu`]], [],
  [ヂョ], [#sansj[ヂョ]], [jo], [#textred[`dyo`]], [],
  [ツ], [#sansj[ツ]], [tsu], [#textlightgrey[`tu`/]`tsu`], [same direction as つ],
  [#textblue[ツァ]], [#textblue[#sansj[ツァ]]], [#textblue[tsa]], [#textblue[`tsa`]], [_Italia "z"_],
  [#textblue[ツィ]], [#textblue[#sansj[ツィ]]], [#textblue[tsi]], [#textblue[`tsi`]], [_Italia "z"_],
  [#textblue[ツェ]], [#textblue[#sansj[ツェ]]], [#textblue[tse]], [#textblue[`tse`]], [_Italia "z"_],
  [#textblue[ツォ]], [#textblue[#sansj[ツォ]]], [#textblue[tso]], [#textblue[`tso`]], [_Italia "z"_],
  [ヅ], [#sansj[ヅ]], [zu], [#textred[`du`]], [],
  [テ], [#sansj[テ]], [te], [`te`], [#underline[te]lephone pole],
  [#textblue[ティ]], [#textblue[#sansj[ティ]]], [#textblue[ti]], [#textred[`texi`]], [_"par#underline[ty]_"],
  [#textblue[テュ]], [#textblue[#sansj[ティ]]], [#textblue[tyu]], [#textred[`texyu`]], [],
  [デ], [#sansj[デ]], [de], [`de`], [],
  [#textblue[ディ]], [#textblue[#sansj[ディ]]], [#textblue[di]], [#textred[`dexi`]], [_"can#underline[dy]_"],
  [#textblue[デュ]], [#textblue[#sansj[デュ]]], [#textblue[dyu]], [#textred[`dexyu`]], [],
  [ト], [#sansj[ト]], [to], [`to`], [#underline[to]tem pole],
  [#textblue[トゥ]], [#textblue[#sansj[トゥ]]], [#textblue[tu]], [#textred[`toxu`]], [_"two"_],
  [ド], [#sansj[ド]], [do], [`do`], [],
  [#textblue[ドゥ]], [#textblue[#sansj[ドゥ]]], [#textblue[du]], [#textred[`dowu`]], [_"dew"_],
  [ナ], [#sansj[ナ]], [na], [`na`], [#underline[na]rwhal],
  [ニ], [#sansj[ニ]], [ni], [`ni`], [same shape as に],
  [ニャ], [#sansj[ニャ]], [nya], [`nya`], [],
  [ニュ], [#sansj[ニュ]], [nyu], [`nyu`], [],
  [ニョ], [#sansj[ニョ]], [nyo], [`nyo`], [],
  [ヌ], [#sansj[ヌ]], [nu], [`nu`], [#underline[noo]dles with chopsticks],
  [ネ], [#sansj[ネ]], [ne], [`ne`], [#underline[ne]ckerchief],
  [ノ], [#sansj[ノ]], [no], [`no`], [long #underline[no]se],
  [ハ], [#sansj[ハ]], [ha], [#textred[`ha`]], [#ruby[八][ハチ] / 八 (CN)],
  [バ], [#sansj[バ]], [ba], [`ba`], [],
  [パ], [#sansj[パ]], [pa], [`pa`], [],
  [ヒ], [#sansj[ヒ]], [hi], [`hi`], [smile #underline[he]he],
  [ヒャ], [#sansj[ヒャ]], [hya], [`hya`], [],
  [ヒュ], [#sansj[ヒュ]], [hyu], [`hyu`], [],
  [ヒョ], [#sansj[ヒョ]], [hyo], [`hyo`], [],
  [ビ], [#sansj[ビ]], [bi], [`bi`], [],
  [ビャ], [#sansj[ビャ]], [bya], [`bya`], [],
  [ビュ], [#sansj[ビュ]], [byu], [`byu`], [],
  [ビョ], [#sansj[ビョ]], [byo], [`byo`], [],
  [ピ], [#sansj[ピ]], [pi], [`pi`], [],
  [ピャ], [#sansj[ピャ]], [pya], [`pya`], [],
  [ピュ], [#sansj[ピュ]], [pyu], [`pyu`], [],
  [ピョ], [#sansj[ピョ]], [pyo], [`pyo`], [],
  [フ], [#sansj[フ]], [fu], [#textlightgrey[`hu`/]`fu`], [#underline[fl]ag],
  [#textblue[ファ]], [#textblue[#sansj[ファ]]], [#textblue[fa]], [#textblue[`fa`]], [],
  [#textblue[フィ]], [#textblue[#sansj[フィ]]], [#textblue[fi]], [#textblue[`fi`]], [],
  [#textblue[フュ]], [#textblue[#sansj[フュ]]], [#textblue[fyu]], [#textblue[`fyu`]], [],
  [#textblue[フェ]], [#textblue[#sansj[フェ]]], [#textblue[fe]], [#textblue[`fe`]], [],
  [#textblue[フォ]], [#textblue[#sansj[フォ]]], [#textblue[fo]], [#textblue[`fo`]], [],
  [ブ], [#sansj[ブ]], [bu], [`bu`], [],
  [プ], [#sansj[プ]], [pu], [`pu`], [],
  [ヘ], [#sansj[ヘ]], [he], [#textred[`he`]], [same shape as へ],
  [ベ], [#sansj[ベ]], [be], [`be`], [],
  [ペ], [#sansj[ペ]], [pe], [`pe`], [],
  [ホ], [#sansj[ホ]], [ho], [`ho`], [#underline[ho]ly cross],
  // [], [], [], [], [],
  [ボ], [#sansj[ボ]], [bo], [`bo`], [],
  [ポ], [#sansj[ポ]], [po], [`po`], [],
  [マ], [#sansj[マ]], [ma], [`ma`], [#underline[ma]th angles],
  [ミ], [#sansj[ミ]], [mi], [`mi`], [#underline[mi]ssiles],
  [ミャ], [#sansj[ミャ]], [mya], [`mya`], [],
  [ミュ], [#sansj[ミュ]], [myu], [`myu`], [],
  [ミョ], [#sansj[ミョ]], [myo], [`myo`], [],
  [ム], [#sansj[ム]], [mu], [`mu`], [cow face, says #underline[moo]],
  [メ], [#sansj[メ]], [me], [`me`], [Arlecchino's eyes (め)],
  [モ], [#sansj[モ]], [mo], [`mo`], [same shape as も],
  [ヤ], [#sansj[ヤ]], [ya], [`ya`], [same shape as や],
  [ユ], [#sansj[ユ]], [yu], [`yu`], [#underline[u]-turn],
  [ヨ], [#sansj[ヨ]], [yo], [`yo`], [#underline[yo]ga pose],
  [ラ], [#sansj[ラ]], [ra], [`ra`], [#underline[ra]ptor],
  [リ], [#sansj[リ]], [ri], [`ri`], [reeds],
  [リャ], [#sansj[リャ]], [rya], [`rya`], [],
  [リュ], [#sansj[リュ]], [ryu], [`ryu`], [],
  [リョ], [#sansj[リョ]], [ryo], [`ryo`], [],
  [ル], [#sansj[ル]], [ru], [`ru`], [tree #underline[roo]ts],
  [レ], [#sansj[レ]], [re], [`re`], [#underline[re]d hair / right side of ル],
  [ロ], [#sansj[ロ]], [ro], [`ro`], [cyclic #underline[ro]ad],
  [ワ], [#sansj[ワ]], [wa], [`wa`], [#underline[wa]termelon slice],
  [ヲ], [#sansj[ヲ]], [wo], [`wo`], [#underline[o]atmeal bowl],
  [ン], [#sansj[ン]], [nn], [#textred[`nn`]], [N/A],
  [ァ], [#sansj[ァ]], [?], [#textlightgrey[`la`/]#textred[`xa`]], [],
  [ィ], [#sansj[ィ]], [?], [#textlightgrey[`li`/]#textred[`xi`]], [],
  [ゥ], [#sansj[ゥ]], [?], [#textlightgrey[`lu`/]#textred[`xu`]], [],
  [ェ], [#sansj[ェ]], [?], [#textlightgrey[`le`/]#textred[`xe`]], [],
  [ォ], [#sansj[ォ]], [?], [#textlightgrey[`lo`/]#textred[`xo`]], [],
  [ャ], [#sansj[ャ]], [?], [#textlightgrey[`lya`/]#textred[`xya`]], [],
  [ュ], [#sansj[ュ]], [?], [#textlightgrey[`lyu`/]#textred[`xyu`]], [],
  [ョ], [#sansj[ョ]], [?], [#textlightgrey[`lyo`/]#textred[`xyo`]], [],
  [ー], [#sansj[ー]], [`<`#super[`+1`]], [#textred[$-$ key]], [],
  [ッ], [#sansj[ッ]], [#super[`+1`]`>`], [#textlightgrey[`ltu`/`ltsu`/#textred[`xtsu`]/]repeat `>`], [],
  hline,
)


== 仮名 Summary

// @typstyle off
#general_table(
  [仮名 summary table. #super[#sym.dagger]Particle romanisation applies only for 平仮名.], // caption
  "tbl:kana-summary",  // label
  6,  // column_sizes
  center,  // column_aligns
  scale_factor: 1,
  hline,
  table.header[#rc(1, 2)[*平仮名*]][#rc(1, 2)[*片仮名*]][*Hepburn*#lb()*romanisation*][*Keyboard*#lb()*command*],
  hline,
  [あ], [#sansj[あ]], [ア], [#sansj[ア]], [a], [`a`],
  [い], [#sansj[い]], [イ], [#sansj[イ]], [i], [`i`],
  [], [], [イェ], [#sansj[イェ]], [ye], [`ye`],
  [う], [#sansj[う]], [ウ], [#sansj[ウ]], [u], [`u`],
  [], [], [ウィ], [#sansj[ウィ]], [wi], [`wi`],
  [], [], [ウェ], [#sansj[ウェ]], [we], [`we`],
  [], [], [ウォ], [#sansj[ウォ]], [wo], [#textred[`uxo`]],
  [], [], [ヴ], [#sansj[ヴ]], [vu], [`vu`],
  [], [], [ヴァ], [#sansj[ヴァ]], [va], [`va`],
  [], [], [ヴィ], [#sansj[ヴィ]], [vi], [`vi`],
  [], [], [ヴュ], [#sansj[ヴュ]], [vyu], [`vyu`],
  [], [], [ヴェ], [#sansj[ヴェ]], [ve], [`ve`],
  [], [], [ヴォ], [#sansj[ヴォ]], [vo], [`vo`],
  [え], [#sansj[え]], [エ], [#sansj[エ]], [e], [`e`],
  [お], [#sansj[お]], [オ], [#sansj[オ]], [o], [`o`],
  [か], [#sansj[か]], [カ], [#sansj[カ]], [ka], [`ka`],
  [が], [#sansj[が]], [ガ], [#sansj[ガ]], [ga], [`ga`],
  [き], [#sansj[き]], [キ], [#sansj[キ]], [ki], [`ki`],
  [きゃ], [#sansj[きゃ]], [キャ], [#sansj[キャ]], [kya], [`kya`],
  [きゅ], [#sansj[きゅ]], [キュ], [#sansj[キュ]], [kyu], [`kyu`],
  [きょ], [#sansj[きょ]], [キョ], [#sansj[キョ]], [kyo], [`kyo`],
  [ぎ], [#sansj[ぎ]], [ギ], [#sansj[ギ]], [gi], [`gi`],
  [ぎゃ], [#sansj[ぎゃ]], [ギャ], [#sansj[ギャ]], [gya], [`gya`],
  [ぎゅ], [#sansj[ぎゅ]], [ギュ], [#sansj[ギュ]], [gyu], [`gyu`],
  [ぎょ], [#sansj[ぎょ]], [ギョ], [#sansj[ギョ]], [gyo], [`gyo`],
  [く], [#sansj[く]], [ク], [#sansj[ク]], [ku], [`ku`],
  [], [], [クァ], [#sansj[クァ]], [kwa], [`kwa`],
  [], [], [クィ], [#sansj[クィ]], [kwi], [`kwi`],
  [], [], [クェ], [#sansj[クェ]], [kwe], [`kwe`],
  [], [], [クォ], [#sansj[クォ]], [kwo], [`kwo`],
  [ぐ], [#sansj[ぐ]], [グ], [#sansj[グ]], [gu], [`gu`],
  [], [], [グァ], [#sansj[グァ]], [gwa], [`gwa`],
  [け], [#sansj[け]], [ケ], [#sansj[ケ]], [ke], [`ke`],
  [げ], [#sansj[げ]], [ゲ], [#sansj[ゲ]], [ge], [`ge`],
  [こ], [#sansj[こ]], [コ], [#sansj[コ]], [ko], [`ko`],
  [ご], [#sansj[ご]], [ゴ], [#sansj[ゴ]], [go], [`go`],
  [さ], [#sansj[さ]], [サ], [#sansj[サ]], [sa], [`sa`],
  [ざ], [#sansj[ざ]], [ザ], [#sansj[ザ]], [za], [`za`],
  [し], [#sansj[し]], [シ], [#sansj[シ]], [shi], [#textlightgrey[`si`/]`shi`],
  [しゃ], [#sansj[しゃ]], [シャ], [#sansj[シャ]], [sha], [`sha`],
  [しゅ], [#sansj[しゅ]], [シュ], [#sansj[シュ]], [shu], [`shu`],
  [], [], [シェ], [#sansj[シュ]], [she], [`she`],
  [しょ], [#sansj[しょ]], [ショ], [#sansj[ショ]], [sho], [`sho`],
  [じ], [#sansj[じ]], [ジ], [#sansj[ジ]], [ji], [#textlightgrey[`zi`/]`ji`],
  [じゃ], [#sansj[じゃ]], [ジャ], [#sansj[ジャ]], [ja], [#textlightgrey[`jya`/]`ja`],
  [じゅ], [#sansj[じゅ]], [ジュ], [#sansj[ジュ]], [ju], [#textlightgrey[`jyu`/]`ju`],
  [], [], [ジェ], [#sansj[ジェ]], [je], [#textlightgrey[`jye`/]`je`],
  [じょ], [#sansj[じょ]], [ジョ], [#sansj[ジョ]], [jo], [#textlightgrey[`jyo`/]`jo`],
  [す], [#sansj[す]], [ス], [#sansj[ス]], [su], [`su`],
  // [], [], [], [], [], [],
  [ず], [#sansj[ず]], [ズ], [#sansj[ズ]], [zu], [`zu`],
  // [], [], [], [], [], [],
  [せ], [#sansj[せ]], [セ], [#sansj[セ]], [se], [`se`],
  [ぜ], [#sansj[ぜ]], [ゼ], [#sansj[ゼ]], [ze], [`ze`],
  [そ], [#sansj[そ]], [ソ], [#sansj[ソ]], [so], [`so`],
  [ぞ], [#sansj[ぞ]], [ゾ], [#sansj[ゾ]], [zo], [`zo`],
  [た], [#sansj[た]], [タ], [#sansj[タ]], [ta], [`ta`],
  [だ], [#sansj[だ]], [ダ], [#sansj[ダ]], [da], [`da`],
  [ち], [#sansj[ち]], [チ], [#sansj[チ]], [chi], [#textlightgrey[`ti`/]`chi`],
  [ちゃ], [#sansj[ちゃ]], [チャ], [#sansj[チャ]], [cha], [`cha`],
  [ちゅ], [#sansj[ちゅ]], [チュ], [#sansj[チュ]], [chu], [`chu`],
  [], [], [チェ], [#sansj[チェ]], [che], [`che`],
  [ちょ], [#sansj[ちょ]], [チョ], [#sansj[チョ]], [cho], [`cho`],
  [ぢ], [#sansj[ぢ]], [ヂ], [#sansj[ヂ]], [ji], [#textred[`di`]],
  [ぢゃ], [#sansj[ぢゃ]], [ヂャ], [#sansj[ヂャ]], [ja], [#textred[`dya`]],
  [ぢゅ], [#sansj[ぢゅ]], [ヂュ], [#sansj[ヂュ]], [ju], [#textred[`dyu`]],
  [ぢょ], [#sansj[ぢょ]], [ヂョ], [#sansj[ヂョ]], [jo], [#textred[`dyo`]],
  [つ], [#sansj[つ]], [ツ], [#sansj[ツ]], [tsu], [#textlightgrey[`tu`/]`tsu`],
  [], [], [ツァ], [#sansj[ツァ]], [tsa], [`tsa`],
  [], [], [ツィ], [#sansj[ツィ]], [tsi], [`tsi`],
  [], [], [ツェ], [#sansj[ツェ]], [tse], [`tse`],
  [], [], [ツォ], [#sansj[ツォ]], [tso], [`tso`],
  [づ], [#sansj[づ]], [ヅ], [#sansj[ヅ]], [zu], [#textred[`du`]],
  [て], [#sansj[て]], [テ], [#sansj[テ]], [te], [`te`],
  [], [], [ティ], [#sansj[ティ]], [ti], [#textred[`texi`]],
  [], [], [テュ], [#sansj[ティ]], [tyu], [#textred[`texyu`]],
  [で], [#sansj[で]], [デ], [#sansj[デ]], [de], [`de`],
  [], [], [ディ], [#sansj[ディ]], [di], [#textred[`dexi`]],
  [], [], [デュ], [#sansj[デュ]], [dyu], [#textred[`dexyu`]],
  [と], [#sansj[と]], [ト], [#sansj[ト]], [to], [`to`],
  [], [], [トゥ], [#sansj[トゥ]], [tu], [#textred[`toxu`]],
  [ど], [#sansj[ど]], [ド], [#sansj[ド]], [do], [`do`],
  [], [], [ドゥ], [#sansj[ドゥ]], [du], [#textred[`dowu`]],
  [な], [#sansj[な]], [ナ], [#sansj[ナ]], [na], [`na`],
  [に], [#sansj[に]], [ニ], [#sansj[ニ]], [ni], [`ni`],
  [にゃ], [#sansj[にゃ]], [ニャ], [#sansj[ニャ]], [nya], [`nya`],
  [にゅ], [#sansj[にゅ]], [ニュ], [#sansj[ニュ]], [nyu], [`nyu`],
  [にょ], [#sansj[にょ]], [ニョ], [#sansj[ニョ]], [nyo], [`nyo`],
  [ぬ], [#sansj[ぬ]], [ヌ], [#sansj[ヌ]], [nu], [`nu`],
  [ね], [#sansj[ね]], [ネ], [#sansj[ネ]], [ne], [`ne`],
  [の], [#sansj[の]], [ノ], [#sansj[ノ]], [no], [`no`],
  [は], [#sansj[は]], [ハ], [#sansj[ハ]], [ha], [#textred[`ha`]],
  [ば], [#sansj[ば]], [バ], [#sansj[バ]], [ba], [`ba`],
  [ぱ], [#sansj[ぱ]], [パ], [#sansj[パ]], [pa], [`pa`],
  [ひ], [#sansj[ひ]], [ヒ], [#sansj[ヒ]], [hi], [`hi`],
  [ひゃ], [#sansj[ひゃ]], [ヒャ], [#sansj[ヒャ]], [hya], [`hya`],
  [ひゅ], [#sansj[ひゅ]], [ヒュ], [#sansj[ヒュ]], [hyu], [`hyu`],
  [ひょ], [#sansj[ひょ]], [ヒョ], [#sansj[ヒョ]], [hyo], [`hyo`],
  [び], [#sansj[び]], [ビ], [#sansj[ビ]], [bi], [`bi`],
  [びゃ], [#sansj[びゃ]], [ビャ], [#sansj[ビャ]], [bya], [`bya`],
  [びゅ], [#sansj[びゅ]], [ビュ], [#sansj[ビュ]], [byu], [`byu`],
  [びょ], [#sansj[びょ]], [ビョ], [#sansj[ビョ]], [byo], [`byo`],
  [ぴ], [#sansj[ぴ]], [ピ], [#sansj[ピ]], [pi], [`pi`],
  [ぴゃ], [#sansj[ぴゃ]], [ピャ], [#sansj[ピャ]], [pya], [`pya`],
  [ぴゅ], [#sansj[ぴゅ]], [ピュ], [#sansj[ピュ]], [pyu], [`pyu`],
  [ぴょ], [#sansj[ぴょ]], [ピョ], [#sansj[ピョ]], [pyo], [`pyo`],
  [ふ], [#sansj[ふ]], [フ], [#sansj[フ]], [fu], [#textlightgrey[`hu`/]`fu`],
  [], [], [ファ], [#sansj[ファ]], [fa], [`fa`],
  [], [], [フィ], [#sansj[フィ]], [fi], [`fi`],
  [], [], [フュ], [#sansj[フュ]], [fyu], [`fyu`],
  [], [], [フェ], [#sansj[フェ]], [fe], [`fe`],
  [], [], [フォ], [#sansj[フォ]], [fo], [`fo`],
  [ぶ], [#sansj[ぶ]], [ブ], [#sansj[ブ]], [bu], [`bu`],
  [ぷ], [#sansj[ぷ]], [プ], [#sansj[プ]], [pu], [`pu`],
  [へ], [#sansj[へ]], [ヘ], [#sansj[ヘ]], [he], [#textred[`he`]],
  [べ], [#sansj[べ]], [ベ], [#sansj[ベ]], [be], [`be`],
  [ぺ], [#sansj[ぺ]], [ペ], [#sansj[ペ]], [pe], [`pe`],
  [ほ], [#sansj[ほ]], [ホ], [#sansj[ホ]], [ho], [`ho`],
  // [], [], [], [], [], [],
  [ぼ], [#sansj[ぼ]], [ボ], [#sansj[ボ]], [bo], [`bo`],
  [ぽ], [#sansj[ぽ]], [ポ], [#sansj[ポ]], [po], [`po`],
  [ま], [#sansj[ま]], [マ], [#sansj[マ]], [ma], [`ma`],
  [み], [#sansj[み]], [ミ], [#sansj[ミ]], [mi], [`mi`],
  [みゃ], [#sansj[みゃ]], [ミャ], [#sansj[ミャ]], [mya], [`mya`],
  [みゅ], [#sansj[みゅ]], [ミュ], [#sansj[ミュ]], [myu], [`myu`],
  [みょ], [#sansj[みょ]], [ミョ], [#sansj[ミョ]], [myo], [`myo`],
  [む], [#sansj[む]], [ム], [#sansj[ム]], [mu], [`mu`],
  [め], [#sansj[め]], [メ], [#sansj[メ]], [me], [`me`],
  [も], [#sansj[も]], [モ], [#sansj[モ]], [mo], [`mo`],
  [や], [#sansj[や]], [ヤ], [#sansj[ヤ]], [ya], [`ya`],
  [ゆ], [#sansj[ゆ]], [ユ], [#sansj[ユ]], [yu], [`yu`],
  [よ], [#sansj[よ]], [ヨ], [#sansj[ヨ]], [yo], [`yo`],
  [ら], [#sansj[ら]], [ラ], [#sansj[ラ]], [ra], [`ra`],
  [り], [#sansj[り]], [リ], [#sansj[リ]], [ri], [`ri`],
  [りゃ], [#sansj[りゃ]], [リャ], [#sansj[リャ]], [rya], [`rya`],
  [りゅ], [#sansj[りゅ]], [リュ], [#sansj[リュ]], [ryu], [`ryu`],
  [りょ], [#sansj[りょ]], [リョ], [#sansj[リョ]], [ryo], [`ryo`],
  [る], [#sansj[る]], [ル], [#sansj[ル]], [ru], [`ru`],
  [れ], [#sansj[れ]], [レ], [#sansj[レ]], [re], [`re`],
  [ろ], [#sansj[ろ]], [ロ], [#sansj[ロ]], [ro], [`ro`],
  [わ], [#sansj[わ]], [ワ], [#sansj[ワ]], [wa], [`wa`],
  [を], [#sansj[を]], [ヲ], [#sansj[ヲ]], [wo], [`wo`],
  [ん], [#sansj[ん]], [ン], [#sansj[ン]], [nn], [#textred[`nn`]],
  [ぁ], [#sansj[ぁ]], [ァ], [#sansj[ァ]], [?], [#textlightgrey[`la`/]#textred[`xa`]],
  [ぃ], [#sansj[ぃ]], [ィ], [#sansj[ィ]], [?], [#textlightgrey[`li`/]#textred[`xi`]],
  [ぅ], [#sansj[ぅ]], [ゥ], [#sansj[ゥ]], [?], [#textlightgrey[`lu`/]#textred[`xu`]],
  [ぇ], [#sansj[ぇ]], [ェ], [#sansj[ェ]], [?], [#textlightgrey[`le`/]#textred[`xe`]],
  [ぉ], [#sansj[ぉ]], [ォ], [#sansj[ォ]], [?], [#textlightgrey[`lo`/]#textred[`xo`]],
  [ゃ], [#sansj[ゃ]], [ャ], [#sansj[ャ]], [?], [#textlightgrey[`lya`/]#textred[`xya`]],
  [ゅ], [#sansj[ゅ]], [ュ], [#sansj[ュ]], [?], [#textlightgrey[`lyu`/]#textred[`xyu`]],
  [ょ], [#sansj[ょ]], [ョ], [#sansj[ョ]], [?], [#textlightgrey[`lyo`/]#textred[`xyo`]],
  [], [], [ー], [#sansj[ー]], [`<`#super[`+1`]], [#textred[$-$ key]],
  [っ], [#sansj[っ]], [ッ], [#sansj[ッ]], [#super[`+1`]`>`], [#textlightgrey[`ltu`/`ltsu`/#textred[`xtsu`]/]repeat `>`],
  hline,
)
