#import "template.typ": * // import everything from template file
#show: template // show everything rule (i.e. the entire document)
#show: appendix("V", 1)

= Interjections and expressions

== Greetings

// @typstyle off
#interjection_and_expression_table(
  [Interections and expressions: greetings. #highlight[TO ORGANISE].], // caption
  "tbl:appendix-vocab-interjections-and-expressions-greetings", // label
  [おはよ], [good morning], [colloquial],
  [おはよう[ございます]], [good morning], [(お#ruby[早][はよ]う[#ruby[御座][ご|ざ]います]); [polite]],
  [こんにちは], [hello/good afternoon/good day], [(#ruby[今日][こん|にち]は)],
  [こんばんは], [good evening], [(#ruby[今晩][こん|ばん]は)],
  [お#ruby[休][やす]み[なさい]], [good night], [],
  // [], [], [],
  hline,
  [お#ruby[疲][つか]れ], [thanks for coming/glad you could make it; thanks for helping], [],
  // [], [], [],
  hline,
  [はじめまして], [nice to meet you/glad to make your acquaintance/how do you do], [(#ruby[始][はじ]めまして)],
  [お#ruby[変][か]わりありませんか], [(after some time apart) how have you been?/nothing untoward has happened, has it?], [polite],
  [よろしくお#ruby[願][ねが]いします/#lb()よろしくお#ruby[願][ねが]いいたします], [I look forward to working with you/please remember me/please treat me favourably/please help me], [(#ruby[宜][よろ]しくお#ruby[願][ねが]い{します/#ruby[致][いた]します}); polite; also in @tbl:appendix-vocab-interjections-and-expressions-exclamations],
  // [], [], [],
  thickhline,
  [ただいま], [I'm home/I'm back], [(#ruby[只今][ただ|いま])],
  [お#ruby[帰][かえ]り[なさい]], [welcome home], [],
  // [], [], [],
  thickhline,
  [ちょっと], [excuse me/hey], [also an adverb],
  [もしもし], [hello (on phone)/excuse me (calling out to someone)], [(#ruby[申][もう]し#ruby[申][もう]し)],
  [お#ruby[久][ひさ]しぶり], [long time no see], [polite],
  [こら], [hey! (calling out to someone); hey! (to scold)], [],
  [こいつ], [hey, you!/you bastard!/damn you!], [derogatory],
  // [], [], [],
  hline,
  [お#ruby[邪魔][じゃ|ま]します], [please excuse my intrusion/I'm coming in ("I'm intruding")], [],
  [#ruby[失礼][しつ|れい]します], [excuse me/I'm sorry/I'm coming in ("I'm being rude")], [polite],
  // [], [], [],
  hline,
  [ちょっとそこまで], [just out for a bit; euphemism for toilet break], [],
  // [], [], [],
  hline,
  [これまで], [that's enough for today], [also a noun],
  [お#ruby[疲][つか]れ#ruby[様][さま]], [thank you for your hard work/good work/see you/goodbye/goodnight], [],
  [また#rruby[明日][あした]], [see you tomorrow], [],
  [またね], [bye/see you later], [],
  [#ruby[行][い]ってくる], [I'm off/see you later], [],
  [#ruby[行][い]ってきます], [I'm off/see you later], [],
  [いってらっしゃい], [have a good day/take care/see you (often in response to #ruby[行][い]ってきます)], [(#ruby[行][い]ってらっしゃい)],
  [お#ruby[邪魔][じゃ|ま]しました], [please excuse my intrusion/I'm leaving ("I intruded")], [],
  [#ruby[失礼][しつ|れい]しました], [excuse me/I'm sorry/I'm leaving ("I was rude")], [polite],
  [お#ruby[先][さき]に#ruby[失礼][しつ|れい]します], [pardon me for leaving first (before everyone else still present)], [],
  [#ruby[気][き]をつけて], [take care/be careful], [#link("https://www.reddit.com/r/LearnJapanese/comments/1gnt92k/what_is_the_difference_between_元気でねお大事に気をつけてね")[[Reddit]]; ((#ruby[気][き]を#ruby[付][つ]けて); also in @tbl:appendix-vocab-interjections-and-expressions-exclamations],
  [お#ruby[大事][だい|じ]に], [get well soon/take care of yourself], [#link("https://www.reddit.com/r/LearnJapanese/comments/1gnt92k/what_is_the_difference_between_元気でねお大事に気をつけてね")[[Reddit]]],
  [#ruby[元気][げん|き]でね], [take care (with nuance of finality)], [#link("https://www.reddit.com/r/LearnJapanese/comments/1gnt92k/what_is_the_difference_between_元気でねお大事に気をつけてね")[[Reddit]]],
  // [], [], [],
  thickhline,
  [ようこそ], [welcome], [],
  [いらっしゃい], [welcome], [honorific; also in @tbl:appendix-vocab-interjections-and-expressions-exclamations],
  [いらっしゃいませ], [welcome (in shops and restaurants)], [],
  [お#ruby[待][ま]たせしました], [thank you for waiting/sorry to have kept you waiting], [polite],
  [いただきます], [thank you for the meal (just served); I receive (this meal)], [(#ruby[頂][いただ]きます)],
  [ごちそうさま[でした]], [thank you for the meal (consumed)], [(ご#ruby[馳走様][ち|そう|さま]\[でした\]); [polite]],
  // [], [], [],
)


== Exclamations

_Read the main article for apologies on #link("https://www.clozemaster.com/blog/sorry-in-japanese/")[CM]._

// @typstyle off
#interjection_and_expression_table(
  [Interections and expressions: exclamations. #highlight[TO ORGANISE].], // caption
  "tbl:appendix-vocab-interjections-and-expressions-exclamations", // label
  [はい], [yes/that is correct/I'm here/pardon?], [],
  [うん], [yes/yeah/mhmm], [],
  [ふむふむ], [hmm/uh-huh; murmur indicating approval/comprehension], [slang],
  [イエス], [yes], [],
  [そう/そうだ/[そうです/そうでございます]], [that's right/indeed (reference to something that was said/done)], [e.g. 「そうだよ」、「そうです」, [polite]],
  [そうそう[...]], [that's right/indeed/that's it (reference to something that was said/done)], [casual],
  [そうそう], [oh, yes!/that's it/indeed/I remember], [],
  [そういえば], [now that you mention it/that reminds me/speaking of which], [],
  [ふむ/ふうむ], [hmm/I see], [],
  // [], [], [],
  hline,
  [#ruby[大丈夫][だい|じょう|ぶ]], [no thanks/I'm good], [(そう#ruby[言][い]えば)],
  [いいえ/いえ], [no], [(#ruby[否][いいえ])],
  [ううん/うーん], [um/well/no], [],
  [ノー], [no/not needed/not allowed], [],
  [ちゃう], [no/that's wrong/it's not like that; isn't it?/wasn't it?], [],
  [もういい], [skip it/drop it; I've had enough/that's enough], [],
  [ご#ruby[遠慮][えん|りょ]いたします], [no thanks/I will refrain], [(ご#ruby[遠慮][えん|りょ]#ruby[致][いた]します); #ruby[遠慮][えん|りょ]の例文から],
  // [], [], [],
  thickhline,
  [お#ruby[願][ねが]い[します]], [please], [[humble]],
  [#ruby[頼][たの]む], [please/please do], [slang, also a verb],
  [{よろしくお#ruby[願][ねが]いします#lb()よろしくお#ruby[願][ねが]いいたします}], [please do/please take care of], [(#ruby[宜][よろ]しくお#ruby[願][ねが]い{します/#ruby[致][いた]します}); polite; also in @tbl:appendix-vocab-interjections-and-expressions-greetings],
  [(お/ご\<nn\>)/\<v-te\>ください], [please do for me], [honorific],
  [ください], [please give me (imperative of くださる)], [(#ruby[下][くだ]さい); honorific],
  [いらっしゃい], [please come/go/stay (polite imperative)], [also in @tbl:appendix-vocab-interjections-and-expressions-greetings],
  [もしよかったら], [if you don't mind/if you like/if you're interested], [(もし#ruby[良][よ]かったら)],
  // [], [], [],
  hline,
  [かしこまりました], [certainly! (in response to superior/customer)], [(#ruby[畏][かしこ]まりました); polite],
  // [], [], [],
  hline,
  [ちゃった], [finished doing/did completely], [slang of しまった/しまいました],
  // [], [], [],
  hline,
  [ご#ruby[遠慮][えん|りょ]ください], [please refrain from], [],
  // [], [], [],
  thickhline,
  [#ruby[気持][き|も]ちいい], [feels good], [also an adjective],
  // [], [], [],
  hline,
  [#ruby[乾杯][かん|ぱい]], [cheers/bottoms-up], [also a verb],
  [うめぇ/うめえ/うめー], [delicious/skilled/good], [colloquial],
  // [], [], [],
  thickhline,
  [その/あの[ー]], [um/er/well/say], [],
  [どれ], [well/now], [also a pronoun],
  [#ruby[何][なん]だ], [what/what the heck/damn], [],
  [#ruby[何][なん]だと], [what did you just say (to me)?/what's that?], [],
  [なんてこと], [my goodness!/good lord!/holy cow!], [],
  [なんてこった], [what the hell/oh great!/son of a X/holy mackerel/oh no!/holy cow!/damn!], [],
  [なんでよ], [why? why not? what's wrong?], [],
  [どうしたの], [what's the matter?/what's wrong?], [],
  [\<nn\>{を/は}どうしたの], [what happened to \<nn\>?/what have you done with \<nn\>?], [],
  // [], [], [],
  hline,
  [どうしよう], [what to do], [],
  [どうするか], [what would you do?/what to do about it?], [],
  // [], [], [],
  hline,
  [かもしれない], [perhaps/possibly (sentence ender)], [(かも#ruby[知][し]れない)],
  [みたいだ], [it seems that; as if], [polite],
  [みたいです], [it seems that; as if], [polite],
  [みたいな], [something like that/sort of like that/similar to that/in that vein], [slang, abbreviation of みたいな#ruby[感][かん]じ],
  // [], [], [],
  hline,
  [ここだけの#ruby[話][はなし]], [confidential talk/conversation between you and me], [],
  // [], [], [],
  thickhline,
  [#ruby[助][たす]けて], [help!], [],
  [#ruby[危][あぶ]ない], [watch out!/look out!/be careful!], [],
  [#ruby[気][き]をつけて], [take care/be careful], [((#ruby[気][き]を#ruby[付][つ]けて); also in @tbl:appendix-vocab-interjections-and-expressions-greetings],
  // [], [], [],
  hline,
  [がんばれ], [hang in there/go for it/keep at it/do your best], [(#ruby[頑張][がん|ば]れ)],
  // [], [], [],
  thickhline,
  [#ruby[悪][わる]い], [my bad/sorry], [casual; also an adjective],
  [#ruby[悪][わる]かった], [my bad/sorry (for past mistake)], [casual; also an adjective],
  [ごめん[ね]], [I'm sorry/excuse me/pardon me], [(#ruby[御免][ご|めん]\[ね\]); casual],
  [ごめんなさい], [I'm sorry/excuse me/pardon me], [(#ruby[御免][ご|めん]なさい); semi-formal],
  [#ruby[許][ゆり]してください], [please forgive me], [(#ruby[許][ゆり]して#ruby[下][くだ]さい); honorific, semi-formal],
  [お#ruby[許][ゆり]しください], [please forgive me], [(お#ruby[許][ゆり]し#ruby[下][くだ]さい); honorific, formal],
  [{#ruby[反省][はん|せい]/#ruby[後悔][こう|かい]\}しています], [I'm sorry ("I am regretful")], [(\{#ruby[反省][はん|せい],#ruby[後悔][こう|かい]}して#ruby[居][い]ます); semi-formal],
  [{#ruby[反省][はん|せい]/#ruby[後悔][こう|かい]\}しております], [I'm sorry ("I am regretful")], [(\{#ruby[反省][はん|せい],#ruby[後悔][こう|かい]}して#ruby[居][お]ります); humble, formal],
  [#ruby[謝罪][しゃ|ざい]いたします], [I'm sorry (esp. in written apology) ("I perform apology")], [(#ruby[謝罪][しゃ|ざい]#ruby[致][いた]します); humble, formal],
  [お#ruby[詫][わ]びいたします], [I'm sorry ("I perform apology")], [(お#ruby[詫][わ]び#ruby[致][いた]します); humble, formal],
  [お#ruby[詫][わ]び#ruby[申][もう]し#ruby[上][あ]げます], [I'm sorry ("I offer my apology")], [humble, formal],
  [#ruby[申][もう]し#ruby[訳][わけ]ない], [I'm sorry/it's inexcusable ("excuse does not exist")], [semi-polite],
  [#ruby[申][もう]し#ruby[訳][わけ]{ございません/ありません}], [I'm sorry/it's inexcusable ("excuse does not exist")], [polite],
  // [], [], [],
  hline,
  [すまん/すいません/[すみません]], [excuse me/pardon me/I'm sorry (general/for the inconvenience)], [(#ruby[済][す]みません); [polite]],
  [#ruby[済][す]まない], [excuse me/I'm sorry], [also an adjective],
  [#ruby[失礼][しつ|れい]しました], [I'm sorry/excuse me/my apologies (general/for the inconvenience)], [polite],
  [ご#ruby[迷惑][めい|わく]をおかけして#ruby[申][もう]し#ruby[訳][わけ]ございません], [We apologise for any inconvenience this may cause (common email/announcement-end greeting) ("I have no excuse for causing you this trouble.")], [polite, formal],
  // [], [], [],
  thickhline,
  [どうも], [thanks (abbreviation)], [],
  [どうもありがとう], [thank you very much], [(どうも#rruby[#"有[り]難"][ありがと]う)],
  [ありがとう[ございます]], [thanks/thank you], [(#rruby[#"有[り]難"][ありがと]う[#ruby[御座][ご|ざ]います]); [polite]],
  [ありがとうございました], [thank you (for past action)], [(#rruby[#"有[り]難"][ありがと]うございました); polite],
  [#ruby[済][す]まない], [thank you], [also an adjective],
  // [], [], [],
  hline,
  [どういたしまして], [you're welcome/don't mention it/not at all/my pleasure], [(どう#ruby[致][いた]しまして)],
  [とんでもない], [it was no bother at all/not at all/don't mention it], [],
  [こちらこそ], [it is I who should say so], [also in @tbl:appendix-vocab-nouns-pronouns-and-question-words],
  [#ruby[気][き]にするな], [don't worry about it/nevermind], [],
  [#ruby[気][き]にしないで], [don't worry about it/forget about it], [],
  [お#ruby[安][や]い#ruby[御用][ご|よう]], [no problem/easy task], [],
  [#ruby[問題][もん|だい]ない], [no problem/not an issue/all right], [also an adjective],
  [#ruby[構][かま]わない], [no problem/it doesn't matter], [],
  [#ruby[構][かま]いません], [no problem/it doesn't matter], [],
  // [], [], [],
  hline,
  [おめでとう[ございます]], [congratulations!/well done!], [(おめでとう[#ruby[御座][ご|ざ]います]); [polite]],
  // [], [], [],
  thickhline,
  [わかる？], [Do you know?/do you think so too?], [(#ruby[分][わ]かる？); also a verb],
  [わかる], [I know/I think so too], [(#ruby[分][わ]かる); also a verb],
  [だろ[う]], [seems/I think/I guess/I wonder/I hope; right?/don't you agree?/I thought you'd say that!], [conjectural form of copula だ],
  [わかんない], [not understanding/not knowing], [(#ruby[分][わ]かんない); slang],
  [どうかな], [how about?/I wonder/I don't know], [],
  // [], [], [],
  hline,
  [なるほど], [I see/that's right/indeed], [(#ruby[成][な]る#ruby[程][ほど])],
  [そうか], [is that so? (rhetorical); I see/right/oh/OK], [],
  [そっか], [oh, right/I see/OK/gotcha], [],
  [そういうことか], [I got it/I see/I now know/so that's the reason], [(そういう#ruby[事][こと]か)],
  [#ruby[了解][りょう|かい]], [OK/roger], [also a noun, verb],
  [よし], [alright/looking good/OK], [],
  // [], [], [],
  hline,
  [そういうことなら], [in that case/that being the case], [],
  // [], [], [],
  thickhline,
  [#ruby[嘘][うそ]], [no way! really!? unbelieveable!], [colloquial],
  [それはそれは], [my goodness (surprise/wonder)], [],
  [まさか], [by no means/never!/no way!], [(#ruby[真逆][ま|さか]); also a noun],
  [まさかの#ruby[時][とき]], [in case of emergency/for a rainy day/in time of need], [],
  [とんでもない], [absolutely not!/far from it!/impossible!/what a thing to say!/no way!], [],
  // [], [], [],
  hline,
  [だから], [like I said/I told you already], [also a conjunction],
  // [], [], [],
  hline,
  [お[お/ー]い/オ[オ/ー]イ], [oi! hey! come on!], [],
  [な], [hey/listen/look/say], [],
  [ほら], [look! see! hey!], [],
  [もう], [jeez/come on], [],
  [まったく[もう]], [good grief], [(#ruby[全][まった]く[もう])],
  [ったく], [good grief], [slang],
  [#ruby[何][なに]か], [what (are you trying to say/do you mean)?], [],
  [え], [eh? what? oh?], [],
  [あれ[っ/え/ー]], [huh? eh? what? look! listen!], [],
  [あら], [oh!/ah!/oh no], [feminine],
  [びっくりした], [oh my god!/oh my gosh!/you got me!/wow! (surprised/frightened)], [],
  [しまった], [darn it!/oops!/oh dear!/oh no!], [],
  [やれ], [oh!/ah!/oh dear!/dear me!/thank God!], [],
  [やれやれ], [oh!/ah!/oh dear!/good grief!/dear me!/thank God!], [],
  // [], [], [],
  hline,
  [やだ/ヤダ], [no way/not a chance], [feminine/childish],
  [そんな], [no way!/never!], [],
  [ふざけんな], [stop messing around!/get real!/screw you!], [slang],
  [ふざけんじゃねー], [stop messing around!/get real!/screw you!], [slang],
  [ざけんなよ], [fuck you!/don't fuck with me!/don't fuck around!], [expletive],
  [ファッキュー], [fuck you], [slang, expletive],
  [そこまで], [stop!/not one step further!], [],
  [いい#ruby[加減][か|げん]にしろ], [that's enough!/cut it out!/get a life!], [],
  [いい#ruby[加減][か|げん]にしなさい], [shape up!/act properly!], [],
  [しっかりしろ], [pull yourself together/get a grip/get a hold of yourself/come on], [],
  [さあ/さー], [come on/come now/come along (to urge/encourage others); here goes (indicates resolve); well (indicates uncertainty/hesitation); about that/actually (interrupting someone)], [],
  [さあて], [well/now/then], [#conjunction],
  // [], [], [],
  hline,
  [クソ], [damn/damn it/shit/crap], [(#ruby[糞][くそ])],
  [この#ruby[野郎][や|ろう]], [you bastard/son of a bitch!], [derogatory],
  [ちくしょう], [damn it/son of a bitch/god damn it], [(#ruby[畜生][ちく|しょう])],
  // [], [], [],
  thickhline,
  [うぜえ], [annoying/noisy], [colloquial],
  [うるさい/うるせ{え/ー\}/うっせ\{え/ー}], [shut up!/be quiet!], [(#ruby[煩][うるさ]い)],
  [#ruby[静][しず]かに], [be quiet!], [also an adverb],
  // [], [], [],
  thickhline,
  [お#ruby[腹][なか]が#ruby[空][す]く], [to become hungry/get an empty stomach], [],
  [#ruby[喉][のど]が#ruby[渇][かわ]く], [to be thirsty], [],
  // [], [], [],
  thickhline,
  [#ruby[以上][い|じょう]], [that's all], [],
  [これ#ruby[以上][い|じょう]], [any more/anymore/any further/any better/any longer (usu. with negative sentence)], [],
  // [], [], [],
  thickhline,
  [つまらない#ruby[物][もの]ですが], [it's not much, but... (when giving a gift)], [humble; (#ruby[詰][つ]まらない#ruby[物][もの]ですが); #link("https://www.youtube.com/shorts/HV4GmjgQZHw")[[KK]]],
  // [], [], [],
  thickhline,
  [ピコーン/ピューン/ピーン], [ding/ping], [#onomatopoeic; manga slang],
  [バチコーン], [thwap/smack (used when winking)], [#link("https://dic.pixiv.net/a/%E3%83%90%E3%83%81%E3%82%B3%E3%83%BC%E3%83%B3")[[PX]]],
  // [], [], [],
  thickhline,
  [#ruby[屁][へ]をひって#ruby[尻][しり]#ruby[窄][つぼ]め], [there is no use shutting the stable door after the horse has bolted ("squeezing your buttocks after you have farted")], [#proverb],
  [#ruby[金言耳][きん|げん|みみ]に#ruby[逆][さか]らう/#ruby[忠言耳][ちゅう|げん|みみ]に#ruby[逆][さか]らう], [good advice is harsh to the ear], [],
  // [], [], [],
)


== Sentence builders

// @typstyle off
#interjection_and_expression_table(
  [Interections and expressions: sentence builders.], // caption
  "tbl:appendix-vocab-interjections-and-expressions-sentence-builders", // label
  [という], [called/named], [(と#ruby[言][い]う)],
  [ということは], [that is to say/so that means], [(と#ruby[言][い]う#ruby[事][こと]は)],
  // [], [], [],
  thickhline,
  [\<basis\>からすると], [judging from/on the basis of/from the point of view of], [],
  [\<basis\>からしたら], [judging from/on the basis of/from the point of view of], [],
  [\<basis\>からすれば], [judging from/on the basis of/from the point of view of], [],
  // [], [], [],
  thickhline,
  [\<about\>ついて], [about/concerning/regarding/as for \<about\>], [(#ruby[就][つ]いて)],
  [\<about\>について], [concerning/regarding \<about\>], [(に#ruby[就][つ]いて)],
  [#ruby[詳][くわ]しくは], [for more details/further information...], [],
  // [], [], [],
  thickhline,
  [するべき], [should do/ought to do], [],
  [すべき], [should do/ought to do], [],
  // [], [], [],
)
