#import "template.typ": * // import everything from template file
#show: template // show everything rule (i.e. the entire document)
#show: appendix("V", 4)

= #ruby[動詞][どう|し] (verbs) <appendix:verbs>


== Physical

// @typstyle off
#verb_table(
  [Verbs: physical.], // caption
  "tbl:appendix-vocab-verbs-physical", // label
  [#ruby[動][うご]かす], [う], [to move/shift/stir/budge/change position; to inspire/mobilise/deploy], [], [#ruby[動][うご]く], [う], [to move; to stir/shift/shake/swing; to be influenced], [],
  [#ruby[移動][い|どう]する], [E], [to move/transfer/migrate], [], [#ruby[移動][い|どう]する], [E], [to move/travel], [],
  [-], [], [], [], [#ruby[運動][うん|どう]する], [E], [to exercise/train/workout/do sports], [],
  [-], [], [], [], [#ruby[活動][かつ|どう]する], [E], [to be active (of person/organisation/animal/volcano/etc.)], [],
  [-], [], [], [], [#ruby[静止][せい|し]する], [E], [to be still/still/dormant (e.g. volcano)], [],
  [-], [], [], [], [#ruby[行動][こう|どう]する], [E], [to act/take action], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[止][と]める], [る], [to stop/turn off; to park; to suppress/hold (cough/tears/breath); to relieve (pain)], [], [#ruby[止][と]まる], [う], [to stop moving/come to a stop/be stopped/perch on (of birds)], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [#ruby[指][さ]す], [う], [to point; to identify/indicate/point out], [], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[触][さわ]る], [う], [to touch/feel (intentional)], [#link("https://dictionary.goo.ne.jp/thsrs/16231/meaning/m1u/")[[goo]]], [#ruby[触][さわ]る], [う], [to touch (intentional)], [#link("https://dictionary.goo.ne.jp/thsrs/16231/meaning/m1u/")[[goo]]],
  [OにSを#ruby[触][ふ]れる], [る], [to touch O using S (unintentional) #highlight[???]], [#link("https://dictionary.goo.ne.jp/thsrs/16231/meaning/m1u/")[[goo]]], [#ruby[触][ふ]れる], [る], [to touch/feel (unintentional); to touch/refer to a subject], [#link("https://dictionary.goo.ne.jp/thsrs/16231/meaning/m1u/")[[goo]]],
  [？], [], [], [], [#ruby[接][せっ]する], [E], [to be close to/in contact (abstract; information/geographical border)], [#link("https://dictionary.goo.ne.jp/thsrs/16231/meaning/m1u/")[[goo]]],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[抱][だ]く], [う], [to embrace/hug/hold in one's arms (e.g. baby)], [], [-], [], [], [],
  [#ruby[抱][だ]きしめる], [る], [to embrace closely/hug someone close/hold someone tight], [(#ruby[抱][だ]き#ruby[締][き]める)], [-], [], [], [],
  [ハグする], [E], [to hug], [], [ハグする], [E], [to hug], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [#ruby[噛][か]む], [う], [to bite/chew], [], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [#ruby[持][も]つ], [う], [to hold (in hand)/take/carry/possess; hold meeting], [], [-], [], [], [],
  [#ruby[押][お]さえる], [る], [to pin down/hold in place/hold steady], [], [-], [], [], [],
  [#ruby[掴][つか]む], [う], [to grab/grasp/grip/clutch/hold], [], [#ruby[掴][つか]まる], [う], [to grasp/hold on to], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [-], [], [], [], [#ruby[座][すわ]る], [う], [to sit/squat], [],
  [#ruby[掛][か]ける], [る], [to sit down/take a seat; to rest against (に-marked)], [], [-], [], [], [],
  [#ruby[腰][こし]を#ruby[掛][か]ける], [る], [to sit down/take a seat], [], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[横][よこ]たえる], [る], [to lay down], [], [#ruby[横][よこ]たわる], [う], [to lie down/stretch out], [],
  [#ruby[伏][ふ]せる], [る], [to turn over/lay face down; to point/cast down (gaze/head)], [also in @tbl:appendix-vocab-verbs-knowledge-truth-and-reality], [#ruby[伏][ふ]せる], [る], [to lie flat on the ground], [],
  [#ruby[残][のこ]す], [う], [to leave behind], [also in @tbl:appendix-vocab-verbs-production], [#ruby[残][のこ]る], [う], [to remain/be left behind], [also in @tbl:appendix-vocab-verbs-production],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [#ruby[押][お]す], [う], [to press/push/exert pressure on; to stamp (seal)], [], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[当][あ]てる], [る], [to hit/put on/hold against; to apply (patch/eye-mask)], [#link("https://ja.hinative.com/questions/3867085")[[HN]]], [#ruby[当][あ]たる], [う], [to be hit/strike (e.g. a target/lottery/by an ailment)], [],
  [#ruby[打][う]つ], [う], [to hit/strike/beat/punch (strong)], [#link("https://dictionary.goo.ne.jp/thsrs/1292/meaning/m0u/")[[goo]]; #link("https://ja.hinative.com/questions/3867085")[[HN]]], [#ruby[打][う]たれる], [る], [to be struck/beaten (strong)], [],
  [#ruby[叩][たた]く], [う], [to (repeatedly) strike/hit/slap/tap/pat/clap (hands); to attack/criticise/flame an idea], [also in @tbl:appendix-vocab-verbs-production; #link("https://dictionary.goo.ne.jp/thsrs/1292/meaning/m0u/")[[goo]]], [-], [], [], [],
  [#ruby[殴][なぐ]る], [う], [to strike/hit/beat/punch someone], [#link("https://dictionary.goo.ne.jp/thsrs/1292/meaning/m0u/")[[goo]]], [-], [], [], [],
  [ぶつ], [う], [to hit someone; strike/beat (stronger)], [(#ruby[打][ぶ]つ); #link("https://dictionary.goo.ne.jp/thsrs/1292/meaning/m0u/")[[goo]]; #link("https://ja.hinative.com/questions/4651279\#answer-39822392")[[HN]]], [？], [], [], [],
  [ぶつける], [る], [to hit someone's head/crash into], [(#ruby[打付][ぶ|つ]ける); #link("https://ja.hinative.com/questions/18725588")[[HN]]], [ぶつかる], [う], [to bump/crash into (large objects)], [#link("https://ja.hinative.com/questions/94519\#answer-237544")[[HN]]],
  [ボコボコにする], [E], [to viciously beat up/hit and kick repeatedly], [slang], [-], [], [], [],
  [ボッコボコにする], [E], [to severely beat up (emphatic)], [slang], [-], [], [], [],
  [しばく], [う], [to strike (with stick/whip); to hit/punch/kick/beat], [], [-], [], [], [],
  [ビンタする], [E], [to slap (esp. in the face)], [], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[刺][さ]す], [う], [to pierce/stab/prick/thrust], [also in @tbl:appendix-vocab-verbs-consumption], [#ruby[刺][さ]さる], [う], [to pierce/get lodged/get stuck into], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[撃][う]つ], [う], [to shoot (gun/person/beam)], [], [-], [], [], [],
  [#ruby[貫通][かん|つう]する], [E], [to pass/go/penetrate/pierce through (of bullet/arrow)], [], [#ruby[貫通][かん|つう]する], [E], [to pass/go/penetrate/pierce through (bullet/arrow)], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[漏][も]らす], [う], [to let leak out (water/light/secret/information)], [], [#ruby[漏][も]れる], [る], [to leak out/escape/shine through], [#link("https://ja.hinative.com/questions/14216491")[[HN]]; #link("https://dictionary.goo.ne.jp/thsrs/15998/meaning/m0u")[[goo]]],
  [バラす], [う], [to expose/disclose/reveal/give away (secret)], [slang], [バレる], [る], [to leaked out/be exposed/be found out (of a secret/lie/improper behaviour)], [slightly casual, #link("https://ja.hinative.com/questions/14216491")[[HN]]],
  [\<v stem\>#ruby[漏][も]らす], [う], [to forget to do \<v stem\>], [#suffix], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [#ruby[振][ふ]り#ruby[返][かえ]る], [#exception[う]], [to turn one's head towards; to think back/reminisce/reflect on], [], [#ruby[振][ふ]り#ruby[返][かえ]る], [#exception[う]], [to turn around/look back], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [#ruby[吐][は]く], [う], [to expel from mouth (breathe/spit/vomit)], [#link("https://dictionary.goo.ne.jp/thsrs/380/meaning/m0u/%E5%90%90%E3%81%8F/")[[goo]]], [-], [], [], [],
  [つく], [う], [to sigh; to tell a lie; to use foul language (all other cases, use #ruby[吐][は]く)], [(#ruby[吐][つ]く); #link("https://ja.hinative.com/questions/12041260")[[HN]]], [-], [], [], [],
  [#ruby[嘘][うそ]をつく], [う], [to tell a lie], [], [-], [], [], [],
  [#ruby[吹][ふ]く], [う], [to blow air through pursed lips], [#link("https://dictionary.goo.ne.jp/thsrs/380/meaning/m0u/%E5%90%90%E3%81%8F/")[[goo]]], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [さらす], [う], [to expose to (sun/danger; に-suffixed); to rinse/soak (vegetables)], [(#ruby[晒][さら]す)], [-], [], [], [],
  [さらす], [う], [to doxx/make someone's private information public], [slang], [-], [], [], [],
  [-], [], [], [], [#ruby[日光浴][にっ|こう|よく]する], [E], [to sunbathe/bask in the sun], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [-], [], [], [], [#ruby[爆発][ばく|はつ]する], [E], [to explode/detonate/blast/blow up/erupt; to outburst/explode/erupt (emotion)], [],
  // [], [], [], [], [], [], [], [],
)


== Directions

// @typstyle off
#verb_table(
  [Verbs: directions.], // caption
  "tbl:appendix-vocab-verbs-directions", // label
  [-], [], [], [], [#ruby[行][い]く], [う], [to go/move through/proceed/reach (information/phase)], [],
  [-], [], [], [], [\<v te\>て[い]く], [う], [{to \<v te\> and go (spatial#lb()to \<v te\> gradually/progressively into the future (temporal)}], [(#ruby[行][い]く); #aux, [formal]],
  [#ruby[持][も]っていく], [う], [to take/bring/carry something along], [], [-], [], [], [],
  [#ruby[進][すす]める], [る], [to advance/move forward], [also in @tbl:appendix-vocab-verbs-courtesy], [#ruby[進][すす]む], [う], [to advance/go forward], [also in @tbl:appendix-vocab-verbs-courtesy],
  // [], [], [], [], [], [], [], [],
  hline,
  [-], [], [], [], [#ruby[急行][きゅう|こう]する], [E], [to hurry/rush to somewhere], [],
  [-], [], [], [], [#ruby[緩行][かん|こう]する], [E], [to go slowly to somewhere], [],
  [#ruby[急][いそ]ぐ], [う], [to hurry (someone to do)/rush/hasten/urge/push/make something happen sooner (oft. causative #ruby[急][いそ]がせる)], [], [#ruby[急][いそ]ぐ], [う], [to hurry/rush], [],
  [-], [], [], [], [#ruby[急][せ]く], [う], [to hurry/rush], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[目指][め|ざ]す], [う], [to aim at/for/to do/to become], [], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [-], [], [], [], [#ruby[去][さ]る], [う], [to leave/go away; to pass/elapse (e.g. seasons)], [also an adjective],
  [-], [], [], [], [#ruby[来][く]る], [E], [to come/approach/arrive], [],
  [-], [], [], [], [#ruby[出][で]て#ruby[来][く]る], [E], [to come out/emerge], [],
  [-], [], [], [], [#ruby[見][み]える], [る], [to come], [honorific; also in @tbl:appendix-vocab-verbs-consumption],
  [-], [], [], [], [\<v te\>てくる], [E], [{to \<v te\> and come back (spatial);#lb()to \<v te\> up to the present (temporal)}], [(#ruby[来][く]る); #aux, #link("https://japanese.stackexchange.com/a/43678")[[SE1]], #link("https://japanese.stackexchange.com/q/48132")[[SE2]]],
  [#ruby[持][も]ってくる], [う], [to take/bring/carry something over], [], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [#ruby[離][はな]す], [う], [to separate/part/divide/keep apart], [], [#ruby[離][はな]れる], [る], [to be separated/apart/distant/disconnected; to leave/go away], [also in @tbl:appendix-vocab-verbs-production],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [-], [], [], [], [#ruby[逆][さか]らう], [う], [to go against/oppose/defy], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[帰][かえ]す], [う], [to send back/home (animate)], [#link("https://ja.hinative.com/questions/23865042")[[HN]]], [#ruby[帰][かえ]る], [#exception[う]], [to return/go back/go home (animate)], [#link("https://ja.hinative.com/questions/23865042")[[HN]]],
  [#ruby[還][かえ]す], [う], [to send back to origin (grander scale)], [#link("https://ja.hinative.com/questions/23865042")[[HN]], #link("https://kurashi-memocho.com/113.html")[[KRS]]], [#ruby[還][かえ]る], [#exception[う]], [to return back to origin (grander scale)], [#link("https://ja.hinative.com/questions/23865042")[[HN]], #link("https://kurashi-memocho.com/113.html")[[KRS]]],
  [#ruby[返][かえ]す], [う], [to return/put something back (inaminate)], [#link("https://ja.hinative.com/questions/23865042")[[HN]]], [#ruby[返][かえ]る], [#exception[う]], [to return/go back (inaminate)], [#link("https://ja.hinative.com/questions/23865042")[[HN]]],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [#ruby[過][す]ごす], [う], [to spend/pass/lead (time/life); to overdo (esp. alcohol consumption)], [], [#ruby[過][す]ぎる], [る], [to pass through/by; to pass (time/life); to have expired], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [？], [], [], [], [#ruby[上][のぼ]る], [う], [to ascend/go up/go upwards (focus on process)], [#link("https://dictionary.goo.ne.jp/word/%E4%B8%8A%E3%82%8B/")[[goo]]],
  [？], [], [], [], [#ruby[登][のぼ]る], [う], [to go to a higher place], [#link("https://dictionary.goo.ne.jp/word/%E4%B8%8A%E3%82%8B/")[[goo]]],
  [？], [], [], [], [#ruby[昇][のぼ]る], [う], [to rise (sun); be promoted in rank], [#link("https://dictionary.goo.ne.jp/word/%E4%B8%8A%E3%82%8B/")[[goo]]],
  [#ruby[上][あ]げる], [る], [to raise; to do up (one's hair); to fly (kite)/launch (fireworks); to land (a boat); to show someone in/away; to enrol (school)], [], [#ruby[上][あ]がる], [う], [to rise (focus on destination); to enter (from outside); to enrol/promote (school); to come ashore; to lift (rain); to spoil/die (e.g. battery)], [#link("https://dictionary.goo.ne.jp/thsrs/15966/meaning/m1u/")[[goo]], #link("https://hugkum.sho.jp/582833")[[HK]]],
  [#ruby[持][も]ち#ruby[上][あ]げる], [る], [to elevate/raise/lift up], [], [-], [], [], [],
  [#ruby[乗][の]せる], [る], [to pick up passenger/load goods], [], [#ruby[乗][の]る], [う], [to board/embark], [],
  [#ruby[拾][ひろ]う], [う], [to pick up (item); book a taxi], [], [-], [], [], [],
  [#ruby[起][お]こす], [う], [to make upright/wake up], [#link("https://dictionary.goo.ne.jp/word/%E8%B5%B7%E3%81%99/")[[goo]]], [#ruby[起][お]きる], [る], [to rise/wake up; to occur (esp. unfavourable incidents)], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [かける], [る], [to hang up/let hang/suspend from/hoist/raise (e.g. coat/painting)], [(#ruby[掛][か]ける)], [かかる], [う], [to hang], [(#ruby[掛][か]かる)],
  [#ruby[壁][かべ]にかける], [る], [to hang on the wall], [(#ruby[壁][かべ]に#ruby[掛][か]ける)], [#ruby[壁][かべ]にかかる], [う], [to hang on the wall], [(#ruby[壁][かべ]に#ruby[掛][か]かる)],
  [], [], [], [], [], [], [], [],
  hline,
  [#ruby[下][くだ]す], [う], [w to make a decision/draw a conclusion (of #ruby[決定][けっ|てい]、#ruby[評決][きょう|けつ]、#ruby[判決][はん|けつ]、#ruby[結論][けつ|ろん])], [], [#ruby[下][くだ]る], [う], [to descend/go down/go downwards (focus on process)], [],
  [#ruby[下][お]ろす], [う], [to take down/bring down/lower (generic, destination often mentioned)], [#link("https://dictionary.goo.ne.jp/thsrs/15980/meaning/m0u/")[[goo]]], [#ruby[下][お]りる], [る], [to go to a lower place], [],
  [？], [], [], [], [#ruby[沈][しず]む], [う], [to set (sun); be sunken/submerged], [],
  [#ruby[下][さ]げる], [る], [to bring down/lower (hinged or small movement)], [#link("https://dictionary.goo.ne.jp/thsrs/15980/meaning/m0u/")[[goo]]], [#ruby[下][さ]がる], [う], [to go downwards_/step backwards_ (focus on destination)], [#link("https://ja.hinative.com/questions/7054838\#answer-36801861")[[HN]]],
  [#ruby[降][お]ろす], [う], [to drop off passenger/unload goods; oust], [], [#ruby[降][お]りる], [る], [to alight/disembark], [],
  [#ruby[落][お]とす], [う], [to drop/let fall; be defeated/rejected; download/copy], [], [#ruby[落][お]ちる], [る], [to fall/drop/collapse/crash (focus on fall); be defeated/fail], [#link("https://ja.hinative.com/questions/22550436")[[HN]]],
  [#ruby[倒][たお]す], [う], [to knock down/turn on its side/recline], [also in @tbl:appendix-vocab-verbs-conflict-and-resolution], [#ruby[倒][たお]れる], [る], [to fall/collapse (focus on ground); to fold/go bankrupt (organisation)], [also in @tbl:appendix-vocab-verbs-conflict-and-resolution; #link("https://ja.hinative.com/questions/22550436")[[HN]]],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[除][のぞ]く], [う], [to exclude/remove (esp. something unnecessary); esp. #ruby[除][のぞ]けば (aside from/excluding)], [#link("https://dictionary.goo.ne.jp/thsrs/2173/meaning/m0u/")[[goo]]], [-], [], [], [],
  [#ruby[退][ど]ける], [る], [to put/move out of the way], [#link("https://dictionary.goo.ne.jp/thsrs/2173/meaning/m0u/")[[goo]], #link("https://ja.hinative.com/questions/22063627")[[HN]]], [どく], [う], [to step aside/move out of the way/make way], [(#ruby[退][ど]く); #link("https://ja.hinative.com/questions/22063627")[[HN]]],
  [#ruby[退][の]ける], [る], [to put/move out of the way (wider usage as auxiliary)], [#link("https://ja.hinative.com/questions/22063627")[[HN]]], [のく], [う], [to step aside/move out of the way/make way (wider usage as auxiliary)], [(#ruby[退][の]く); #link("https://ja.hinative.com/questions/22063627")[[HN]]],
  [どかす], [う], [to remove/move out of the way], [(#ruby[退][ど]かす)], [-], [], [], [],
  [#ruby[押][お]しのける], [る], [to physically push aside], [(#ruby[押][お]し#ruby[退][の]ける)], [-], [], [], [],
  [-], [], [], [], [#ruby[立][た]ち#ruby[退][の]く], [う], [to evict/evacuate/be displaced], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [-], [], [], [], [#ruby[左折][さ|せつ]する], [E], [to make a left turn], [],
  [-], [], [], [], [#ruby[右折][う|せつ]する], [E], [to make a right turn], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[戻][もど]す], [う], [to put back/return/revert state/turn back (clock hand)], [], [#ruby[戻][もど]る], [う], [to turn back/return/go back], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [-], [], [], [], [#ruby[降][ふ]る], [う], [to fall (rain/snow/ash); to beam down (sunlight/moonlight/luck/misfortune)], [],
  thickhline,
  [#ruby[入][い]れる], [る], [to put in/bring in/let in/insert/install (software)], [], [#ruby[入][はい]る], [#exception[う]], [to enter/arrive/join/get into/fit into], [#link("https://ja.hinative.com/questions/15301215")[[HN]]],
  [-], [], [], [], [#ruby[立][た]ち#ruby[入][い]る], [#exception[う]], [to trespass/intrude/interfere/pry/delve deeper], [],
  [\<stem\>#ruby[込][こ]む], [う], [to go/put into; to completely become; to do thoroughly/sufficiently; to remain (seated/silent)], [], [-], [], [], [],
  [#ruby[差][さ]し#ruby[込][こ]む], [う], [to insert/put/thrust/plug in; to shine/stream in (light)], [#suffix], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [-], [], [], [], [#ruby[入店][にゅう|てん]する], [E], [to enter a store/restaurant; to become an employee at a store], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[出][だ]す], [う], [to take out/get out/publish/send (letter)/produce], [CN 出～], [#ruby[出][で]る], [る], [to exit/leave/come out/flow/appear/answer (phone/door)], [incl. CN 出～ usages],
  // [],
  [#ruby[取][と]り#ruby[出][だ]す], [う], [to take out/pick out; to retrieve/recover], [#link("https://dictionary.goo.ne.jp/thsrs/1970/meaning/m0u/")[[goo]]], [-], [], [], [],
  [\<v stem\>#ruby[出][だ]す], [う], [to begin to \<v stem\>; to \<v stem\> out (e.g. jump out, carry out)], [#suffix], [-], [], [], [],
  [#ruby[追][お]い#ruby[出][だ]す], [う], [to expel/drive/chase out], [], [-], [], [], [],
  [#ruby[抜][ぬ]く], [う], [to pull out/extract/unplug; to omit/skip/pass; to steal], [#link("https://dictionary.goo.ne.jp/thsrs/1970/meaning/m0u/")[[goo]]], [#ruby[抜][ぬ]ける], [る], [to come out/fall out/be extracted; be omitted/missing], [],
  [#ruby[抜][ぬ]け#ruby[出][だ]す], [う], [to slip out/sneak away/break free], [], [#ruby[抜][ぬ]け#ruby[出][で]る], [る], [to slip out/steal out], [],
  [#ruby[抜][ぬ]き#ruby[出][だ]す], [う], [to pick/single/select out], [#link("https://dictionary.goo.ne.jp/thsrs/1970/meaning/m0u/")[[goo]]], [？], [], [], [],
  [\<v stem>#ruby[抜][ぬ]く], [う], [to do thoroughly/completely/to the end], [#suffix], [], [], [], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [#ruby[減][へ]らす], [う], [to decrease], [], [#ruby[減][へ]る], [#exception[う]], [to decrease], [],
  [#ruby[増][ふ]やす], [う], [to increase], [], [#ruby[増][ふ]える], [る], [to increase], [],
  [-], [], [], [], [#ruby[相当][そう|とう]する], [E], [to correspond/be equivalent (in meaning/function); to be proportionate to; to be worthy/deserving of], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [#ruby[開][あ]ける], [る], [to open (business/general; revealing vacant space)], [#link("https://www.tofugu.com/japanese/akeru-aku-hirakeru-hiraku/")[[TFG]]], [#ruby[開][あ]く], [う], [to open (business/general; revealing vacant space)], [#link("https://dictionary.goo.ne.jp/thsrs/16355/meaning/m0u/")[[goo]], #link("https://ja.hinative.com/question_summaries/350008")[[HN]], #link("https://www.tofugu.com/japanese/akeru-aku-hirakeru-hiraku/")[[TFG]]],
  [#ruby[開][ひら]く], [う], [to open (focus on non-linear unfolding movement)], [#link("https://dictionary.goo.ne.jp/thsrs/16355/meaning/m0u/")[[goo]], #link("https://ja.hinative.com/question_summaries/350008")[[HN]], #link("https://www.tofugu.com/japanese/akeru-aku-hirakeru-hiraku/")[[TFG]]], [#ruby[開][ひら]く], [う], [to open (focus on non-linear unfolding movement)], [#link("https://dictionary.goo.ne.jp/thsrs/16355/meaning/m0u/")[[goo]], #link("https://ja.hinative.com/question_summaries/350008")[[HN]], #link("https://www.tofugu.com/japanese/akeru-aku-hirakeru-hiraku/")[[TFG]]],
  [-], [], [], [], [#ruby[開][ひら]ける], [る], [to unfold (figurative/formal; view/development/path forward)], [#link("https://www.tofugu.com/japanese/akeru-aku-hirakeru-hiraku/")[[TFG]]],
  [#ruby[空][あ]ける], [る], [to clear/empty out/make space; leave/be temporarily away], [], [-], [], [], [],
  [-], [], [], [], [#ruby[明][あ]ける], [る], [to dawn/begin (day/new year); leave schedule free/make time for], [],
  [], [], [], [], [], [], [], [],
  hline,
  [#ruby[閉][と]じる], [う], [to close/shut (business/general/non-linear folding)], [#link("https://dictionary.goo.ne.jp/thsrs/16377/meaning/m1u/")[[goo]], #link("https://japanese.stackexchange.com/a/32676")[[SE]]], [#ruby[閉][と]じる], [う], [to close/shut (business/general/non-linear folding)], [#link("https://dictionary.goo.ne.jp/thsrs/16377/meaning/m1u/")[[goo]], #link("https://japanese.stackexchange.com/a/32676")[[SE]]],
  [#ruby[閉][し]める], [る], [to close/shut (focus on linear movement)], [#link("https://dictionary.goo.ne.jp/thsrs/16377/meaning/m1u/")[[goo]], #link("https://japanese.stackexchange.com/a/32676")[[SE]]], [#ruby[閉][し]まる], [う], [to close/shut (focus on linear movement); to be closed (shops)], [#link("https://japanese.stackexchange.com/a/32676")[[SE]]],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [-], [], [], [], [#ruby[昇進][しょう|しん]する], [E], [to be promoted/rise in rank (of person)], [#link("https://dictionary.goo.ne.jp/thsrs/8994/meaning/m0u/")[[goo]]],
  [-], [], [], [], [#ruby[昇格][しょう|かく]する], [E], [to be promoted in status (of person/institution)], [#link("https://dictionary.goo.ne.jp/thsrs/8994/meaning/m0u/")[[goo]]],
  [-], [], [], [], [#ruby[昇任][しょう|にん]する], [E], [to be promoted/advance (of person)], [#link("https://dictionary.goo.ne.jp/thsrs/8994/meaning/m0u/")[[goo]]],
  [#ruby[格上][かく|あ]げする], [E], [to promote/upgrade to (に-marked)], [], [-], [], [], [],
  [-], [], [], [], [#ruby[昇級][しょう|きゅう]する], [E], [to upgrade/promote/advance in grade/class/rank], [#link("https://dictionary.goo.ne.jp/thsrs/8994/meaning/m0u/")[[goo]]],
  // [], [], [], [], [], [], [], [],
  [-], [], [], [], [#ruby[降格][こう|かく]する], [E], [to be demoted/drop in rank (of person/institution)], [],
  [-], [], [], [], [#ruby[降任][こう|にん]する], [E], [to be demoted (of person)], [],
  [#ruby[格下][かく|さ]げする], [E], [to demote/downgrade to (に-marked)], [], [-], [], [], [],
  [-], [], [], [], [#ruby[降級][こう|きゅう]する], [E], [to downgrade/demote/degrade in grade/class/rank], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [#ruby[呼吸][こ|きゅう]する], [E], [to breathe], [], [#ruby[呼吸][こ|きゅう]する], [E], [to breathe/respire], [],
  // [], [], [], [], [], [], [], [],
)


== Clothing
#link("https://japanesewithkanako.com/how-to-say-wear-in-japanese/")[#highlight[TO READ]]
#link("https://www.linguajunkie.com/japanese/to-wear-in-japanese")[#highlight[TO READ]]
#link("https://www.youtube.com/watch?v=w_uJJyGkzZo")[#highlight[TO READ]]
#link("https://www.facebook.com/watch/?v=1437814793073414")[#highlight[TO READ]]

// @typstyle off
#verb_table(
  [Verbs: clothing.], // caption
  "tbl:appendix-vocab-verbs-clothing", // label
  [つける 付ける], [], [], [], [], [], [], [],
  thickhline,
  [かぶる], [う], [to put on (head)/be covered with/shoulder responsibility], [(#ruby[被][かぶ]る); #link("https://www.instagram.com/p/DDRcHfGS9T4/")[[IG]]], [-], [], [], [],
  [かける], [る], [to wear/put on (glasses/coat)], [(#ruby[掛][か]ける)], [-], [], [], [],
  [メガネをかける], [る], [to wear/put on glasses], [(#rruby[眼鏡][めがね]を#ruby[掛][か]ける)], [-], [], [], [],
  [#ruby[着][き]る], [る], [to wear (upper body)], [#link("https://www.instagram.com/p/DDRcHfGS9T4/")[[IG]]], [-], [], [], [],
  [{#ruby[履][は]く#lb()#ruby[穿][は]く}], [う], [to put on (lower body: pants, skirt, shoes)], [#link("https://www.instagram.com/p/DDRcHfGS9T4/")[[IG]]], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [#ruby[脱][ぬ]ぐ], [う], [to take off/undress (head/upper body/lower body)], [#link("https://www.instagram.com/p/DDRcHfGS9T4/")[[IG]]], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [#ruby[着替][き|が]える], [る], [to change one's clothes], [], [#ruby[着替][き|が]える], [る], [to change one's clothes], [],
  // [], [], [], [], [], [], [], [],
)


== Emotions

// @typstyle off
#verb_table(
  [Verbs: emotions.], // caption
  "tbl:appendix-vocab-verbs-emotions", // label
  [#ruby[想][おも]う], [う], [to think/feel (heart-felt nuance)], [], [-], [], [], [],
  [#ruby[感][かん]じる], [る], [to feel/experience], [], [-], [], [], [],
  [#ruby[感][かん]じ#ruby[取][と]る], [う], [to perceive/sense], [], [-], [], [], [],
  [-], [], [], [], [#ruby[気][き]がする], [E], [to feel (as if; usu. after 〜たい/された); to feel like doing (usu. negative)], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [#ruby[喜][よろこ]ぶ], [う], [to be delighted/pleased by; to congratulate; to welcome (proposal/advice)], [], [#ruby[喜][よろこ]ぶ], [う], [to be delighted/glad/pleased/rejoice], [],
  [-], [], [], [], [#ruby[笑][わら]う], [う], [to laugh; to smile; to sneer/ridicule], [#link("https://dictionary.goo.ne.jp/thsrs/883/meaning/m0u/")[[goo]]],
  [-], [], [], [], [#rruby[微笑][ほほえ]む], [う], [to smile], [#link("https://dictionary.goo.ne.jp/thsrs/883/meaning/m0u/")[[goo]]],
  [-], [], [], [], [ニヤニヤする], [E], [to grin/smirk], [],
  [#ruby[嘲笑][ちょう|しょう]する], [E], [to scorn/ridicule/sneer at], [], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [-], [], [], [], [#ruby[幸][しあわ]せにする], [E], [to bring someone happiness/make someone happy], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [?], [], [], [], [#ruby[震][ふる]える], [る], [to shiver/quiver/tremble (e.g. cold/fear/rage)], [],
  [-], [], [], [], [#ruby[緊張][きん|ちょう]する], [E], [to be nervous/stressed/tense], [],
  [#ruby[心配][しん|ぱい]する], [E], [to worry/fear about], [], [-], [], [], [],
  [], [], [], [], [ビビる], [#exception[う]], [to feel nervous/afraid/self-conscious; [to be startled/surprised/shocked/frightened/spooked]], [[slang]],
  [#ruby[悩][なや]ます], [う], [to worry/trouble/torment/burden/harass], [], [#ruby[悩][なや]む], [う], [to be worried/troubled], [],
  [-], [], [], [], [ソワソワする], [E], [to be restless/nervous/uneasy/in a fidget], [#onomatopoeic],
  [-], [], [], [], [イライラする], [E], [to be irritated/annoyed; to fret/worry/be on the edge; to be impatient/lose patience], [(#ruby[苛々][いら|いら]する); #onomatopoeic],
  [#ruby[後悔][こう|かい]する], [E], [to regret/repent], [], [#ruby[後悔][こう|かい]する], [E], [to be regretful/remorseful], [],
  [#ruby[反省][はん|せい]する], [E], [to reflect/introspect; to regret/repent], [], [-], [], [], [],
  [-], [], [], [], [ツンツンする], [E], [to be prickly/standoffish/cold/aloof], [also an adverb],
  [-], [], [], [], [ムカムカする], [E], [to feel sick/queasy/nauseated/disgusted], [also an adverb],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[誇][ほこ]りに#ruby[思][おも]う], [う], [to be proud of (neutral connotation)], [#link("https://ja.hinative.com/questions/15541270")[[HN]]], [], [], [], [],
  [#ruby[誇][ほこ]る], [う], [to be proud of/take pride in (neutral connotation)], [], [-], [], [], [],
  [#ruby[自慢][じ|まん]する], [E], [to boast of (negative connotation)], [#link("https://ja.hinative.com/questions/15541270")[[HN]]], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[激励][げき|れい]する], [E], [to encourage/spur on/cheer on], [], [-], [], [], [],
  [#ruby[励][はげ]ます], [う], [to encourage/cheer on/cheer up], [], [-], [], [], [],
  [#ruby[気合][き|あい]をかける], [る], [to cheer on/raise a shout to someone (に-marked)], [(#ruby[気合][き|あい]を#ruby[掛][か]ける)], [#ruby[気合][き|あい]を#ruby[入][い]れる], [る], [to fire/psych/motivate oneself up; to give it one's all],
  [-], [], [], [], [#ruby[努力][ど|りょく]する], [E], [to put in effort/exert/endeavour/strive], [],
  [-], [], [], [], [#ruby[無理][む|り]する], [E], [to work/try too hard], [], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[噛][か]み#ruby[殺][ころ]す], [う], [to stifle (yawn/smile/laugh/etc.)], [], [-], [], [], [],
  [#ruby[笑][わら]いを#ruby[噛][か]み#ruby[殺][ころ]す], [う], [to stifle a laugh], [], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[抑][おさ]える], [る], [to restrain/control (emotions); to keep within limits (spending)], [], [-], [], [], [],
  [#ruby[遠慮][えん|りょ]する], [E], [to refrain from (esp. タバコ)], [], [#ruby[遠慮][えん|りょ]する], [E], [to hold back/reserve/constrain/restrain oneself], [],
  [#ruby[配慮][はい|りょ]する], [E], [to be considerate/thoughtful of], [], [#ruby[配慮][はい|りょ]する], [E], [to have consideration/thoughtfulness for (に-marked)], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[切望][せつ|ぼう]する], [E], [to earnestly desire/eagerly hope/long/yearn for (usu. progressive)], [], [-], [], [], [],
  [-], [], [], [], [#ruby[絶望][ぜつ|ぼう]する], [E], [to despair/feel hopeless], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [-], [], [], [], [#ruby[感動][かん|どう]する], [E], [to be emotionally deeply moved/excited/inspired (internal emotions)], [#link("https://dictionary.goo.ne.jp/thsrs/3581/meaning/m1u/")[[goo]]],
  [-], [], [], [], [#ruby[感激][かん|げき]する], [E], [to be emotionally deeply moved/impressed/inspired (stronger; with observable behavioural change)], [#link("https://dictionary.goo.ne.jp/thsrs/3581/meaning/m1u/")[[goo]]],
  [-], [], [], [], [#ruby[興奮][こう|ふん]する], [E], [to be excited/stimulated/agitated/aroused], [],
  [#ruby[傷][きず]つける], [る], [to wound/injure/hurt someone's feelings], [], [#ruby[傷][きず]つく], [う], [to be wounded/injured/hurt (feelings)], [],
  [-], [], [], [], [#ruby[泣][な]く], [う], [to cry], [],
  [-], [], [], [], [#ruby[泣][な]ける], [る], [to shed tears/be moved to tears], [],
  [#ruby[理解][り|かい]する], [E], [to sympathise], [also in @tbl:appendix-vocab-verbs-education-and-correctness], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[怒][おこ]らす], [う], [to anger/offend/provoke], [(esp. 怒らせる)], [#ruby[怒][おこ]る], [う], [to get angry/lose one's temper; to scold/tell someone off], [],
  [-], [], [], [], [ブチ#ruby[切][き]れる], [る], [to become enraged/lose it/flip out/blow one's top], [slang],
  [-], [], [], [], [キレる], [る], [to snap/flip/get angry/lose one's temper], [(#ruby[切][き]れる)],
  [#ruby[嫉妬][しっ|と]する], [E], [to be jealous of (something)], [], [#ruby[嫉妬][しっ|と]する], [E], [to be jealous (of (に-marked person))], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [-], [], [], [], [#ruby[落][お]ち#ruby[着][つ]く], [う], [to calm down/compose oneself/relax; to settle down (location/job)], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [-], [], [], [], [びっくりする], [E], [to be surprised/frightened/startled], [],
  [#ruby[脅][おど]かす], [う], [to startle/frighten/scare], [also in @tbl:appendix-vocab-verbs-conflict-and-resolution], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [#ruby[大切][たい|せつ]にする], [E], [to cherish/treasure], [also an adjective, adverb], [-], [], [], [],
  [#ruby[愛][あい]する], [E], [to love], [], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [#ruby[楽][たの]しむ], [う], [to enjoy/take pleasure in/have a good time/have fun (also used in wishes)], [], [-], [], [], [],
  [#ruby[楽][たの]しみにする], [E], [to look forward to], [], [-], [], [], [],
  [-], [], [], [], [ドキドキする], [E], [to beat fast (heart)/throb/pound/palpitate], [also an adverb],
  [-], [], [], [], [ワクワクする], [E], [to be excited/thrilled/nervous], [also an adverb],
  // [], [], [], [], [], [], [], [],
)


== Production

// @typstyle off
#verb_table(
  [Verbs: production.], // caption
  "tbl:appendix-vocab-verbs-production", // label
  [#ruby[作][つく]る], [う], [to make/prepare (food)/grow (agriculture)/cultivate (people)], [#link("https://dictionary.goo.ne.jp/word/%E4%BD%9C%E3%82%8B")[[goo]]], [-], [], [], [],
  [#ruby[造][つく]る], [う], [to construct (large-scale buildings, manufacturing)], [#link("https://dictionary.goo.ne.jp/word/%E4%BD%9C%E3%82%8B")[[goo]]], [-], [], [], [],
  [#ruby[創][つく]る], [う], [to create/compose (artistic)/start a business], [#link("https://dictionary.goo.ne.jp/word/%E4%BD%9C%E3%82%8B")[[goo]]], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  hline,
  // [], [], [], [], [], [], [], [],
  [かける], [る], [to pour/splash/throw into (liquid); to sprinkle onto (powder/spice)], [(#ruby[掛][か]ける)], [-], [], [], [],
  [#ruby[塩][しお]をかける], [る], [to salt/sprinkle salt on], [(#ruby[塩][しお]を#ruby[掛][か]ける)], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [つける], [る], [to affix/attach/join/apply; to assign; to tail/watch], [(#ruby[付][つ]ける); also in @tbl:appendix-vocab-verbs-clothing], [#ruby[付][つ]く], [つく], [to come with/be provided/attached; to stain/scar/dye], [],
  [つなぐ], [う], [to connect/link together; to tie/chain/restrain], [(#ruby[繋][つな]ぐ); also in @tbl:appendix-vocab-verbs-interaction], [つながる], [う], [to be tied/connected/linked/chained to; to be related to], [(#ruby[繋][つな]がる)],
  [-], [], [], [], [#ruby[血][ち]がつながる], [う], [to be related by blood (usu. as progressive #ruby[血][ち]がつながっている)], [(#ruby[血][ち]が#ruby[繋][つな]がる)],
  [#ruby[札][ふだ]をつける], [る], [to affix a label/tag], [(#ruby[札][ふだ]を#ruby[付][つ]ける)], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[加][くわ]える], [る], [to add/include/sum (objects/people/concepts); to increase (heat/influence/speed)], [], [#ruby[加][くわ]わる], [う], [to participate/be added to (objects/people/concepts); to increase (heat/influence/speed)], [],
  [#ruby[付][つ]け#ruby[加][くわ]える], [る], [to add on/supplement/append], [], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [#ruby[足][た]す], [う], [to add (arithmetic)], [also: プラス[する]; #link("https://japanese.stackexchange.com/a/56967")[[SE]]], [-], [], [], [],
  [#ruby[引][ひ]く], [う], [to subtract (arithmetic)], [also: マイナスする; #link("https://japanese.stackexchange.com/a/56967")[[SE]]], [-], [], [], [],
  [かける], [る], [to multiply (arithmetic)], [(#ruby[掛][か]ける); #link("https://japanese.stackexchange.com/a/56967")[[SE]]], [-], [], [], [],
  [#ruby[割][わ]る], [う], [to divide (arithmetic)], [#link("https://japanese.stackexchange.com/a/56967")[[SE]]], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [#ruby[始][はじ]める], [る], [to start/begin/initiate], [#link("https://ja.hinative.com/questions/4515521")[[HN]]], [#ruby[始][はじ]まる], [う], [to start/begin], [#link("https://ja.hinative.com/questions/4515521")[[HN]]],
  [スタートする], [E], [to start/begin], [], [スタートする], [E], [to start/begin], [],
  [#ruby[開始][かい|し]する], [E], [to start/commence/begin/initiate], [slightly formal, #link("https://ja.hinative.com/questions/4515521")[[HN]]], [#ruby[開始][かい|し]する], [E], [to start/commence/begin/initiate], [slightly formal, #link("https://ja.hinative.com/questions/4515521")[[HN]]],
  [-], [], [], [], [#ruby[出発][しゅっ|ぱつ]する], [E], [to depart/leave/set off], [],
  [#ruby[発動][はつ|どう]する], [E], [kick-start/put into effect (activity/feeling/machine/policy)], [], [#ruby[発動][はつ|どう]する], [E], [to kick-start into effect (activity/feeling/machine/policy)], [],
  [#ruby[起動][き|どう]する], [E], [to startup/boot up/activate], [], [#ruby[起動][き|どう]する], [E], [to startup/boot up/activate], [],
  [#ruby[準備][じゅん|び]する], [E], [to prepare/arrange/get ready/setup], [], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[管理][かん|り]する], [E], [to manage/control (e.g. business)], [], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[残][のこ]す], [う], [to leave undone; to be left over/remain], [also in @tbl:appendix-vocab-verbs-physical], [#ruby[残][のこ]る], [う], [to be left undone; to be left over/remaining], [also in @tbl:appendix-vocab-verbs-physical],
  [#ruby[続][つづ]ける], [る], [to continue], [], [#ruby[続][つづ]く], [う], [to continue], [],
  [\<v stem\>#ruby[続][つづ]ける], [る], [to continue \<v stem\>], [#aux], [], [], [], [],
  [-], [], [], [], [#ruby[引][ひ]き#ruby[続][つづ]く], [う], [to continue (for a long time); to come next (TV)], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [やめる], [る], [to stop/end/quit/cancel/abandon/refrain], [(#ruby[止][や]める)], [#ruby[止][や]む], [う], [to stop/cease/be over], [],
  [#ruby[辞][や]める], [る], [to resign/retire/quit a job], [], [-], [], [], [],
  [#ruby[諦][あきら]める], [る], [to give up/resign/abandon], [], [-], [], [], [],
  [-], [], [], [], [#ruby[離][はな]れる], [る], [to quit/give up], [also in @tbl:appendix-vocab-verbs-directions],
  [-], [], [], [], [いい#ruby[加減][か|げん]にする], [E], [to put an end to/get over with/quit something someone's been stuck doing], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [\<stem\>#ruby[止][さ]す], [う], [to stop in the midst of], [#suffix], [-], [], [], [],
  [#ruby[終][お]える], [る], [to finish], [#link("https://ja.hinative.com/questions/2620397")[[HN]]], [#ruby[終][お]わる], [う], [to end/finish], [#link("https://ja.hinative.com/questions/2620397")[[HN]]],
  [#ruby[終了][しゅう|りょう]する], [E], [to end/close/terminate], [slightly formal, #link("https://ja.hinative.com/questions/2620397")[[HN]]], [#ruby[終了][しゅう|りょう]する], [E], [to end/close/terminate], [slightly formal, #link("https://ja.hinative.com/questions/2620397")[[HN]]],
  [\<v stem\>#ruby[終][お]える], [る], [to finish \<v stem\>], [#aux], [], [], [], [],
  [#ruby[完成][かん|せい]する], [E], [to complete/finish], [], [-], [], [], [],
  [-], [], [], [], [#ruby[突破][とっ|ぱ]する], [E], [to break through/overcome; to exceed], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[披露][ひ|ろう]する], [E], [to announce/unveil/introduce; to boast], [], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [-], [], [], [], [#ruby[引退][いん|たい]する], [E], [to retire (from the workforce)], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[登録][とう|ろく]する], [E], [to be entered into a register/to register/subscribe (YouTube)], [#link("https://dictionary.goo.ne.jp/word/%e7%99%bb%e9%8c%b2/")[[goo]]], [], [], [], [],
  [-], [], [], [], [#ruby[入会][にゅう|かい]する], [E], [to enrol/admit into a club/society/mailing list], [#link("https://ja.hinative.com/questions/22502664")[[HN]]],
  [-], [], [], [], [#ruby[加入][か|にゅう]する], [E], [to join a group/project], [#link("https://ja.hinative.com/questions/22502664")[[HN]]],
  [-], [], [], [], [#ruby[退会][たい|かい]する], [E], [to withdraw/resign from a club/society/mailing list], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [#ruby[書][か]く], [う], [to write], [], [？], [], [], [],
  [#ruby[描][か]く], [う], [to draw/paint], [], [？], [], [], [],
  [#ruby[描][えが]く], [う], [to imagine; to depict (abstract concept)], [], [？], [], [], [],
  [#ruby[書][か]き#ruby[直][なお]す], [う], [to rewrite], [], [-], [], [], [],
  [メモする], [E], [to note], [], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [#ruby[言][い]う], [う], [to say; to name/call], [], [-], [], [], [],
  [#ruby[言][い]い#ruby[出][だ]す], [う], [to start saying], [], [-], [], [], [],
  [#ruby[言][い]いさす], [う], [to stop saying midway], [(#ruby[言][い]い#ruby[止][さ]す)], [-], [], [], [],
  [#ruby[話][はな]す], [う], [to talk/speak], [], [-], [], [], [],
  [-], [], [], [], [ささやく], [う], [to whisper/murmur; to spread rumour (oft. passive progressive)], [(#ruby[囁][ささや]く)],
  [-], [], [], [], [しゃべる], [#exception[う]], [to chat/chatter/talk], [(#ruby[喋][しゃべ]る)],
  [#ruby[呼][よ]ぶ], [う], [to call out to; to name/call; to summon (e.g. doctor)], [], [-], [], [], [],
  [#ruby[放送][ほう|そう]する], [E], [to broadcast/be on air (TV/radio)], [#link("https://hinative.com/questions/21999375")[[HN]]], [-], [], [], [],
  [#ruby[配信][はい|しん]する], [E], [to broadcast/stream (Internet)], [#link("https://hinative.com/questions/21999375")[[HN]]], [-], [], [], [],
  [-], [], [], [], [#ruby[雑談][ざつ|だん]する], [E], [to chat/idle talk], [],
  [アドバイスする], [E], [to advise], [], [-], [], [], [],
  [#ruby[申][もう]し#ruby[上][あ]げる], [る], [to say/express/offer/extend (greetings/congratulations/apologies, etc.)], [humble, also in @tbl:appendix-vocab-verbs-interaction], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [-], [], [], [], [#ruby[黙][だま]る], [う], [to be silent/say nothing], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[歌][うた]う], [う], [to sing], [], [#ruby[歌][うた]う], [う], [to sing], [],
  [#ruby[演奏][えん|そう]する], [E], [to perform/play (music/instrument)], [], [-], [], [], [],
  [#ruby[叩][たた]く], [う], [to play (drum)], [also in @tbl:appendix-vocab-verbs-physical], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [-], [], [], [], [#ruby[踊][おど]る], [う], [to dance (a hopping dance)], [],
  [-], [], [], [], [#ruby[小躍][こ|おど]りする], [E], [to dance for joy], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [-], [], [], [], [#ruby[歩][ある]く], [う], [to walk], [],
  [-], [], [], [], [ぶらぶらする], [E], [to walk leisurely/aimlessly], [#onomatopoeic, also an adverb],
  [-], [], [], [], [#ruby[散歩][さん|ぽ]する], [E], [to take a stroll], [],
  [-], [], [], [], [#ruby[走][はし]る], [#exception[う]], [to run; drive (vehicle); flash (lightning); wind (road)], [],
  [-], [], [], [], [#ruby[走][はし]り#ruby[出][だ]す], [う], [to start running/break into a run], [],
  [#ruby[追][お]う], [う], [to chase/run after/pursue], [], [-], [], [], [],
  [#ruby[追][お]いかける], [る], [to chase/run after/pursue], [(#ruby[追][お]い#ruby[掛][か]ける)], [], [], [], [],
  [#ruby[追][お]い#ruby[込][こ]む], [う], [to corner/go hard/push/force someone into doing; to herd/drive/chase ("chase into")], [], [], [], [], [],
  [-], [], [], [], [#ruby[時間][じ|かん]に#ruby[追][お]われる], [to be pressed for time ("chased by time")], [], [],
  [-], [], [], [], [#ruby[追][お]いつく], [う], [to catch up with (chase/relationships) ("chase and attach")], [(#ruby[追][お]い#ruby[付][つ]く)],
  // [], [], [], [], [], [], [], [],
  hline,
  [-], [], [], [], [#ruby[泳][およ]ぐ], [う], [to swim/weave through a crowd], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [-], [], [], [], [#ruby[混雑][こん|ざつ]する], [E], [to be congested/crowded/jammed], [#link("https://japanese.stackexchange.com/a/103694")[[SE]]],
  [-], [], [], [], [#ruby[混][こ]む], [う], [to be crowded/packed/congested], [#link("https://japanese.stackexchange.com/a/103694")[[SE]]],
  [-], [], [], [], [#ruby[空][す]く], [う], [to become less crowded/thin out; to get empty], [also in @tbl:appendix-vocab-verbs-health],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [#ruby[逃][に]がす], [う], [to miss/fail to catch (more physical); to set free/let go/release (physical)], [#link("https://dictionary.goo.ne.jp/thsrs/1605/meaning/m0u/%E9%80%83%E3%81%8C%E3%81%99/")[[goo]]], [#ruby[逃][にげ]げる], [る], [to flee/escape/get away/avoid (danger/responsibility)], [],
  [#ruby[逃][のが]す], [う], [to miss/fail to catch (more abstract); to put out of reach (abstract)], [#link("https://dictionary.goo.ne.jp/thsrs/1605/meaning/m0u/%E9%80%83%E3%81%8C%E3%81%99/")[[goo]]], [#ruby[逃][のが]れる], [る], [to escape], [],
  [\<v stem\>#ruby[逃][のが]す], [う], [to fail to \<v stem\>], [#aux], [], [], [], [],
  [#ruby[取][と]り#ruby[逃][に]がす], [う], [to try and catch but fail], [#link("https://dictionary.goo.ne.jp/thsrs/1605/meaning/m0u/%E9%80%83%E3%81%8C%E3%81%99/")[[goo]]], [-], [], [], [],
  [#ruby[逸][いっ]する], [E], [to miss/deviate from (abstract only; chance/right track)], [#link("https://dictionary.goo.ne.jp/thsrs/1605/meaning/m0u/%E9%80%83%E3%81%8C%E3%81%99/")[[goo]]], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[避][さ]ける], [る], [to avoid (physical/situation/question/responsibility)], [], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [#ruby[取][と]る], [う], [to take (notes/break/time)/obtain/pass/obtain], [], [#ruby[取][と]れる], [る], [to come off (button/handle/lid)], [],
  [とる], [う], [to have/take/consume (a meal/vitamins)], [(#ruby[摂][と]る)], [], [], [], [],
  [#ruby[盗][ぬす]む], [う], [to steal/plagiarise], [], [-], [], [], [],
  [#ruby[手][て]に#ruby[入][い]れる], [る], [to obtain/get/procure/win/secure], [], [#ruby[手][て]に#ruby[入][はい]る], [#exception[う]], [to obtain/get one's hands on], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[撮][と]る], [う], [to take a photograph], [], [#ruby[撮][と]れる], [る], [to be taken (photograph)], [],
  [#ruby[録][と]る], [う], [to record an audio or video], [], [#ruby[録][と]れる], [る], [to be recorded/caught on tape (audio or video)], [],
  [#ruby[捕][と]る], [う], [to catch an object/capture an animal], [], [#ruby[捕][と]れる], [る], [to be caught (object)/captured (animal)], [],
  [#ruby[採][と]る], [う], [to adopt (method/proposal); to collect/gather (flowers/plants)], [], [#ruby[採][と]れる], [る], [to be collected/gathered (flowers/plants)], [],
  [#ruby[摘][つ]む], [う], [to pick/pluck (flowers); to nip/snip/cut/trim], [], [つまむ], [う], [to pick up (with chopsticks/tweezers)/pinch/hold], [],
  [もぐ], [う], [to pick/pluck by twisting from a tree], [], [-], [], [], [],
  [#ruby[集][あつ]める], [る], [to collect/assemble/gather (collectibles/people/information)], [], [#ruby[集][あつ]まる], [う], [to assemble/gather/collect], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [#ruby[計算][けい|さん]する], [E], [to calculate/compute], [], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [#ruby[守][まも]る], [う], [to protect/guard/defend], [also in @tbl:appendix-vocab-verbs-conflict-and-resolution], [-], [], [], [],
  [#ruby[面倒][めん|どう]を#ruby[見][み]る], [る], [to look after (#exception[の]-marked)], [], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[切][き]る], [#exception[う]], [to cut/open (sealed); turn off (lights/appliance); hang up; (conversation); shuffle/discard (cards/tiles); punch (ticket)], [], [#ruby[切][き]れる], [る], [to break/snap; run out/stop working/expire; be disconnected; be shuffled (cards/tiles); run out (stock); break up], [],
  [\<v stem\>#ruby[切][き]る], [#exception[う]], [#highlight[to be able to] do \<v stem\> completely], [#aux], [], [], [], [],
  [#ruby[破][やぶ]る], [う], [to tear/rip (paper/cloth); to break through (defences); to surpass (record)], [#link("https://ja.hinative.com/questions/17387132")[[HN]]; also in @tbl:appendix-vocab-verbs-conflict-and-resolution], [#ruby[破][やぶ]れる], [る], [to break/collapse/be torn/worn out/ruined], [],
  [#ruby[壊][こわ]す], [う], [to break/destroy/demolish (general physical); to wreck/ruin/spoil/damage/destroy (e.g. dreams)], [#link("https://ja.hinative.com/questions/17387132")[[HN]]], [#ruby[壊][こわ]れる], [る], [to break/fall apart/collapse/be broken/destroyed/damaged; to stop working], [],
  [#ruby[粉砕][ふん|さい]する], [E], [to pulverise/crush/reduce to pieces], [], [-], [], [], [],
  [-], [], [], [], [もげる], [る], [to be torn off/come off], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[直][なお]す], [う], [to repair/correct (mistake/habit)/restore/tidy up (hair/make-up)/fix], [], [#ruby[直][なお]る], [う], [to return to normal/be restored/repaired/improved/corrected], [],
  [#ruby[治][なお]す], [う], [to cure/heal], [], [#ruby[治][なお]る], [う], [to recover/be cured/healed], [],
  [\<v stem\>#ruby[直][なお]す], [う], [to redo \<v stem\>], [-], [], [], [], [],
  [#ruby[訂正][てい|せい]する], [E], [to correct/amend (something that is clearly wrong)], [#link("https://ja.hinative.com/questions/19269939")[[HN]]], [-], [], [], [],
  [#ruby[調整][ちょう|せい]する], [E], [to adjust/tune/tailor], [], [-], [], [], [],
  [#ruby[改修][かい|しゅう]する], [E], [to modify (nuance of repurposing for new purpose)], [], [-], [], [], [],
  [#ruby[修正][しゅう|せい]する], [E], [to amend/correct/revise/modify/alter/retouch/update/fix], [#link("https://ja.hinative.com/questions/19269939")[[HN]]], [-], [], [], [],
  [#ruby[手直][て|なお]しする], [E], [to modify (nuance of pushing an incomplete product towards completion)], [], [-], [], [], [],
  [#ruby[添削][てん|さく]する], [E], [to correct by adding/removing (usu. in education)], [#link("https://ja.hinative.com/questions/19269939")[[HN]]], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[世話][せ|わ]する], [E], [to care/look after; to put up a good word for/recommend/introduce], [], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [#ruby[温][あたた]める], [る], [to warm/heat up moderately], [(also #ruby[暖][あたた]める); #link("https://dictionary.goo.ne.jp/thsrs/12980/meaning/m0u/")[[goo]]], [温#ruby[ま][ま]る], [う], [to warm oneself up], [],
  [#ruby[熱][ねっ]する], [E], [to heat to high temperature; to get excited/fired up], [#link("https://dictionary.goo.ne.jp/thsrs/12980/meaning/m0u/")[[goo]]], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[冷][ひ]やす], [う], [to cool from room temperature/chill/refrigerate (any object); to calm down/regain composure/relax], [#link("https://dictionary.goo.ne.jp/thsrs/13001/meaning/m0u/")[[goo]], #link("https://ja.hinative.com/questions/18888717")[[HN2]]], [#ruby[冷][ひ]える], [る], [to be cooled (more than usual/purposefully from room temperature) (any subject)], [#link("https://ja.hinative.com/questions/14831720")[[HN1]], #link("https://ja.hinative.com/questions/18888717")[[HN2]]],
  [#ruby[冷][さ]ます], [う], [to cool from high temperature to room temperature (of liquid/food/heat); to dampen (feelings/atmosphere/interest)], [#link("https://dictionary.goo.ne.jp/thsrs/13001/meaning/m0u/")[[goo]], #link("https://ja.hinative.com/questions/18888717")[[HN2]]], [#ruby[冷][さ]める], [る], [to cool down/become cold (naturally) (liquid/food/heat)], [#link("https://ja.hinative.com/questions/14831720")[[HN1]], #link("https://ja.hinative.com/questions/18888717")[[HN2]]],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [#ruby[洗][あら]う], [う], [to wash/cleanse/rinse], [], [-], [], [], [],
  [#ruby[掃除][そう|じ]する], [E], [to clean/sweep/dust/scrub], [#link("https://dictionary.goo.ne.jp/thsrs/6207/meaning/m0u/")[[goo]]], [-], [], [], [],
  [#ruby[清掃][せい|そう]する], [E], [to clean/clean-up/garbage collect], [literary; #link("https://dictionary.goo.ne.jp/thsrs/6207/meaning/m0u/")[[goo]]], [-], [], [], [],
  [#ruby[掃][は]く], [う], [to sweep/brush/clean], [], [-], [], [], [],
  [#ruby[払][はら]う], [う], [to brush/dust/wipe off (e.g. dust/dirt)], [also in @tbl:appendix-vocab-verbs-consumption], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [-], [], [], [], [#ruby[求婚][きゅう|こん]する], [E], [to propose (marriage)], [],
  [-], [], [], [], [#ruby[結婚][けっ|こん]する], [E], [to get/be married], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [-], [], [], [], [#ruby[咲][さ]く], [う], [to bloom/flower/blossom], [],
  [-], [], [], [], [#ruby[満開][まん|かい]する], [E], [to be in full bloom (esp. of cherry blossom)], [],
  // [], [], [], [], [], [], [], [],
)


== Consumption

// @typstyle off
#verb_table(
  [Verbs: consumption.], // caption
  "tbl:appendix-vocab-verbs-consumption", // label
  [#ruby[使][つか]う], [う], [to use (something/person/idea/means/method)], [#link("https://dictionary.goo.ne.jp/thsrs/1943/meaning/m0u/")[[goo]]], [-], [], [], [],
  [#ruby[用][もち]いる], [る], [to use (slightly abstract); to evaluate and use (person); to adopt (idea)], [#link("https://dictionary.goo.ne.jp/thsrs/1943/meaning/m0u/")[[goo]]], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [かける], [る], [to spend/expend/use (time/money)], [(#ruby[掛][か]ける)], [かかる], [う], [to take/require (time/money)], [(#ruby[掛][か]かる)],
  [#ruby[時間][じ|かん]をかける], [る], [to spend time (on doing something)], [(#ruby[時間][じ|かん]を#ruby[掛][か]ける)], [#ruby[時間][じ|かん]がかかる], [う], [to take/require time], [(#ruby[時間][じ|かん]が#ruby[掛][か]かる)],
  [#ruby[請求][せい|きゅう]する], [E], [to charge/bill (for a service)], [also in @tbl:appendix-vocab-verbs-interaction], [-], [], [], [],
  [#ruby[払][はら]う], [う], [to pay (money/bill)], [also in @tbl:appendix-vocab-verbs-production], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[遊][あそ]ばす], [う], [to leave idle (resources)], [], [-], [], [], [],
  [#ruby[遊][あそ]ばせる], [る], [to leave idle (resources)], [], [-], [], [], [],
  [-], [], [], [], [#ruby[寝][ね]る], [る], [to lie idle (resources)], [also in @tbl:appendix-vocab-verbs-health],
  [-], [], [], [], [#ruby[睡][ねむ]る], [う], [to lie idle (resources)], [also in @tbl:appendix-vocab-verbs-health],
  // [], [], [], [], [], [], [], [],
  hline,
  [-], [], [], [], [なくなる], [う], [to run out/be reduced to zero/not occur anymore], [(#ruby[無][な]くなる); also in @tbl:appendix-vocab-verbs-knowledge-truth-and-reality],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [#ruby[見][み]る], [る], [to see/observe], [], [#ruby[見][み]える], [る], [to be seen/visible], [also in @tbl:appendix-vocab-verbs-directions],
  [ちらっと#ruby[見][み]る], [る], [to glimpse/glance at], [], [-], [], [], [],
  [\<v te\>みる], [る], [to try \<v te\> and see (what happens)], [#aux], [-], [], [], [],
  [#ruby[試][こころ]みる], [う], [to attempt/try and see if it's possible], [#link("https://dictionary.goo.ne.jp/thsrs/9516/meaning/m0u")[[goo]]], [-], [], [], [],
  [#ruby[試][ため]す], [う], [to attempt/put to the test and confirm truth/goodness], [#link("https://dictionary.goo.ne.jp/thsrs/9516/meaning/m0u")[[goo]]], [-], [], [], [],
  [#ruby[見][み]つける], [る], [to find/discover/detect], [], [#ruby[見][み]つかる], [う], [to be found/discovered], [],
  [バラす], [う], [to expose/disclose/leak a secret], [colloquial], [バレる], [る], [to be exposed/found out/leak a secret], [],
  [#ruby[実験][じっ|けん]する], [う], [to experiment], [#link("https://dictionary.goo.ne.jp/thsrs/9516/meaning/m0u")[[goo]]], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [#ruby[読][よ]む], [う], [to read/recite/pronounce/decipher], [], [-], [], [], [],
  [#ruby[読][よ]み#ruby[出][だ]す], [う], [to read out (computing)], [], [-], [], [], [],
  [#ruby[読][よ]みさす], [う], [to leave half-read], [(#ruby[読][よ]み#ruby[止][さ]す)], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [#ruby[聞][き]く], [う], [to hear], [], [#ruby[聞][き]こえる], [る], [to be heard/audible], [],
  [#ruby[聴][き]く], [う], [to listen attentively (music)], [], [？], [], [], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [#ruby[吸][す]う], [う], [to smoke (cigarettes); to breathe in/inhale; to soak up/absorb (sponge); to kiss], [], [-], [], [], [],
  [タバコを#ruby[吸][す]う], [う], [to smoke a cigarette], [], [-], [], [], [],
  [#ruby[吸][す]い#ruby[込][こ]む], [う], [to inhale/breathe in; to soak up/absorb (sponge); to suck in (allure)], [], [-], [], [], [],
  [-], [], [], [], [キスする], [E], [to kiss (に-marked)], [],
  [-], [], [], [], [チュッする], [E], [to lightly kiss/smooch], [slang, #onomatopoeic],
  [-], [], [], [], [チューする], [E], [to kiss], [slang, #onomatopoeic],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [#ruby[食][た]べる], [る], [to eat], [], [-], [], [], [],
  [#ruby[食][く]う], [う], [to eat (masculine); to bite/sting (insects); to consume (resources)], [also in @tbl:appendix-vocab-verbs-conflict-and-resolution], [-], [], [], [],
  [#ruby[刺][さ]す], [う], [to sting/bite (insects)], [also in @tbl:appendix-vocab-verbs-physical], [-], [], [], [],
  [#ruby[食][た]べすぎる], [る], [to overeat], [], [-], [], [], [],
  [#ruby[味][あじ]わう], [う], [to taste/experience/savour/relish (literal/abstract (e.g. victory))], [], [-], [], [], [],
  [-], [], [], [], [\<adj\>#ruby[味][あじ]がする], [E], [to taste like/of], [],
  [テイクアウトする], [E], [to take-out/takeaway food], [], [-], [], [], [],
  [#ruby[持][も]ち#ruby[帰][かえ]る], [#exception[う]], [to take home/take out (food)], [], [-], [], [], [],
  [#ruby[摂取][せっ|しゅ]する], [E], [to intake/ingest (salt/sugar/pills/food); to absorb/assimilate (knowledge/culture)], [], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[飲][の]む], [う], [to drink/swallow/take medicine], [], [-], [], [], [],
  [#ruby[呑][の]む], [う], [to gulp/swallow whole], [], [-], [], [], [],
  [-], [], [], [], [#ruby[乾杯][かん|ぱい]する], [E], [to toast/drink/drink one's glass dry (in honour of/celebration)], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [つける], [る], [to turn on/switch on/light up (appliance/fire)], [(#ruby[点][つ]ける)], [つく], [う], [to come on/ignite/be turned on/lit (appliance/fire)], [(#ruby[点][つ]く)],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[消][け]す], [う], [to erase/delete/rid; turn off/extinguish (appliance/fire)], [], [#ruby[消][き]える], [る], [to disappear/vanish; go out/be turned off/extinguished (appliance/fire)], [],
  [-], [], [], [], [なくなる], [う], [to disappear (e.g. pain/dream)], [(#ruby[無][な]くなる); also in @tbl:appendix-vocab-verbs-knowledge-truth-and-reality],
  [#ruby[削除][さく|じょ]する], [E], [to delete/erase/eliminate], [], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [#ruby[遊][あそ]ぶ], [う], [to play], [], [], [], [], [],
  [#ruby[遊][あそ]ばす], [う], [to let someone play; to entertain/amuse someone], [], [-], [], [], [],
  [#ruby[遊][あそ]ばせる], [る], [to let someone play; to entertain/amuse someone], [], [-], [], [], [],
  [-], [], [], [], [ふざける], [る], [to joke/make fun of], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [#ruby[買][か]う], [う], [to buy], [], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [ロックする], [E], [to lock], [], [-], [], [], [],
  [かける], [る], [to secure (lock)], [(#ruby[掛][か]ける)], [かかる], [う], [to be fastened (lock)], [(#ruby[掛][か]かる)],
  [#ruby[鍵][かぎ]をかける], [る], [to lock up (e.g. door)], [(#ruby[鍵][かぎ]を#ruby[掛][か]ける)], [#ruby[鍵][かぎ]がかかる], [う], [to become locked/be locked], [(#ruby[鍵][かぎ]が#ruby[掛][か]かる)],
  // [], [], [], [], [], [], [], [],
)


== Interaction

// @typstyle off
#verb_table(
  [Verbs: interaction.], // caption
  "tbl:appendix-vocab-verbs-interaction", // label
  [-], [], [], [], [ある], [う], [to exist/have (inaminate)], [(#ruby[有][あ]る)],
  [-], [], [], [], [いる], [る], [to exist (animate)], [(#ruby[居][い]る)],
  [-], [], [], [], [\<v te\>ている], [る], [progressive state of action/being], [(#ruby[居][い]る); #aux],
  [-], [], [], [], [\<adj/v stem\>すぎる], [る], [to be excessive/too much], [(#ruby[過][す]ぎる); #suffix],
  // [], [], [], [], [], [], [], [],
  hline,
  [?], [], [], [], [する], [E], [to do], [],
  [?], [], [], [], [{お/ご}\<nn\>#ruby[申][もう]し#ruby[上][あ]げる], [る], [to do], [#aux; humble, also in @tbl:appendix-vocab-verbs-production],
  [?], [], [], [], [\<nn\>にする], [E], [to decide on (e.g. ordering from menu)], [],
  [?], [], [], [], [\<adj\>にする], [E], [to make become], [],
  [?], [], [], [], [\<v\>ことにする], [E], [to decide to \<v\>], [],
  [?], [], [], [], [\<v\>ことにしている], [E], [to decide to make it a rule/practice to \<v\>], [],
  [?], [], [], [], [\<v\>ようにする], [E], [to try to make sure that \<v\>], [],
  [やる], [う], [to do/play/send/put; to give (to animal)], [(#ruby[遣][や]る/#ruby[行][や]る); slang], [], [], [], [],
  [やってみる], [る], [to have a go/try and do], [(やって#ruby[見][み]る)], [やってみる], [る], [to take a chance with something], [(やって#ruby[見][み]る)],
  [?], [], [], [], [ゴリ#ruby[押][お]しする], [E], [to do/push through by force], [],
  [#ruby[捧][ささ]げる], [る], [to dedicate/offer/devote/sacrifice], [], [-], [], [], [#lb() % technically there is a 捧ぐ but I think nobody really uses that so...],
  [しまう], [う], [to finish/stop/close/shut down/put away], [(#ruby[仕舞][し|ま]う)], [-], [], [], [],
  [\<v te\>しまう], [う], [to do completely], [(#ruby[仕舞][し|ま]う); #aux], [-], [], [], [],
  [\<v te\>しまう], [う], [to do accidentally], [(#ruby[仕舞][し|ま]う); #aux], [-], [], [], [],
  [{\<vtf\>ちゃう#lb()\<vtf\>じゃう}], [う], [to do completely], [#aux], [-], [], [], [],
  [{\<vtf\>ちゃう#lb()\<vtf\>じゃう}], [う], [to do accidentally], [#aux], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [-], [], [], [], [なる], [う], [to become/get/attain/reach/turn into/be completed], [usu. 「〜になる」],
  [?], [], [], [], [ご\<noun\>になる], [う], [to do \<noun\>], [#aux, honorific],
  [?], [], [], [], [お\<v stem\>になる], [う], [to do \<v stem\>], [#aux, honorific],
  [?], [], [], [], [\<v\>ことになる], [う], [to arrange/decide so that \<v\>], [],
  [?], [], [], [], [\<v\>ようになる], [う], [to come to be that/start to \<v\> (focus on change state)], [],
  [?], [], [], [], [よくなる], [う], [to become better/improve], [(#ruby[良][よ]くなる)],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [#ruby[表][あらわ]す], [う], [to represent/stand for; to express (e.g. emotions)], [], [#ruby[表][あらわ]れる], [る], [to be expressed (e.g. emotions)], [],
  [#ruby[現][あらわ]す], [う], [to reveal/show/display], [], [#ruby[現][あらわ]れる], [る], [to appear/become visible/become apparent/materialise], [],
  [#ruby[表][表]する], [E], [to express/show], [formal, literary], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [#ruby[置][お]く], [う], [to leave behind/put/place], [], [-], [], [], [],
  [\<v te\>ておく], [う], [to do \<v te\> in advance in preparation for something], [], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[選][えら]ぶ], [う], [to choose/select], [], [-], [], [], [],
  [#ruby[優先][ゆう|せん]する], [E], [to precede/take priority/be preferred], [], [#ruby[優先][ゆう|せん]する], [E], [to take precedence/priority over others], [],
  [-], [], [], [], [#ruby[間][ま]に#ruby[合][あ]う], [う], [to be good enough/make do], [also in @tbl:appendix-vocab-verbs-courtesy],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [-], [], [], [], [いる], [る], [to need/want], [(#ruby[要][い]る)],
  [お#ruby[願][ねが]いする], [E], [to request/ask for a favour/wish], [polite], [-], [], [], [],
  [#ruby[頼][たの]む], [う], [to request/ask/beg; to entrust to; to rely on], [], [-], [], [], [],
  [#ruby[請求][せい|きゅう]する], [E], [to request/apply for; to demand/claim (e.g. luggage, damages)], [also in @tbl:appendix-vocab-verbs-consumption], [-], [], [], [],
  [#ruby[任][まか]せる], [る], [to entrust/leave to someone (に-suffixed)], [#link("https://ja.hinative.com/questions/1251943")[[HN]]], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[命令][めい|れい]する], [E], [to order/command], [], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [-], [], [], [], [\<nn\>に#ruby[関][かん]する], [E], [concerning/relating/regarding \<nn\>], [],
  [-], [], [], [], [#ruby[関係][かん|けい]する], [E], [to be related/connected to (human relationships); to participate in/be involved/concerned with], [],
  [-], [], [], [], [#ruby[関連][かん|れん]する], [E], [to be related/connected to (abstract/general)], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [-], [], [], [], [#ruby[会][あ]う], [う], [to meet/encounter], [],
  [-], [], [], [], [#ruby[逢][あ]う], [う], [to meet/encounter (close friends/romantic)], [#link("https://ja.hinative.com/questions/22148235")[[HN]]],
  [-], [], [], [], [#ruby[遭][あ]う], [う], [to have an undesired meeting/experience/accident], [],
  [-], [], [], [], [できる], [る], [to come into existence; to make/get friend/partner], [(#ruby[出来][で|き]る); also in @tbl:appendix-vocab-verbs-ability],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[誘][さそ]う], [う], [to invite; to ask someone to do/take someone along to (に-marked)], [], [-], [], [], [],
  [おごる], [う], [to treat someone to something (e.g. a meal/drink)], [(#ruby[奢][おご]る)], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [-], [], [], [], [#ruby[答][こた]える], [る], [to answer/reply], [],
  [-], [], [], [], [#ruby[返事][へん|じ]する], [E], [to reply/answer/response], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [#ruby[待][ま]つ], [う], [to wait], [], [#ruby[待][ま]つ], [う], [to wait], [],
  [#ruby[楽][たの]しみに#ruby[待][ま]つ], [う], [to wait expectantly/in anticipation], [], [#ruby[楽][たの]しみに#ruby[待][ま]つ], [う], [to wait expectantly/in anticipation], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [#ruby[一緒][いっ|しょ]にする], [E], [to do together/unite/mix], [], [], [], [], [],
  [[\<with list\>と] #ruby[一緒][いっ|しょ]になる], [う], [to rendezvous/join/meet together/get married with], [\htc], [], [], [], [],
  [-], [], [], [], [#ruby[目立][め|だ]つ], [う], [to stand out/be conspicuous], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [-], [], [], [], [#ruby[変][か]わった], [る], [to be unusual/abnormal/strange/odd/peculiar/weird/different], [],
  [-], [], [], [], [#ruby[変][か]わっている], [る], [to be unusual/uncommon/peculiar/eccentric/different], [sometimes derogatory],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [#ruby[送][おく]る], [う], [to send/dispatch/forward/transmit/ship/remit/pass; to see someone off/bid farewell; to affix (#ruby[送][おく]り#ruby[仮名][が|な])], [], [-], [], [], [],
  [#ruby[贈][おく]る], [う], [to gift (a present)], [], [-], [], [], [],
  [#ruby[送][おく]り#ruby[出][だ]す], [う], [to send out/forward; to show a person out], [], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[受][う]ける], [る], [to receive/get; to be struck by (e.g. winds/waves/sunlight)], [], [-], [], [], [],
  [いただく], [う], [to receive/accept/take/eat/drink], [(#ruby[頂][いただ]く); humble], [いただける], [る], [to be able to receive/accept/eat/drink], [humble],
  [\<v te\>いただく], [う], [to receive (humble of もらう)], [humble], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [ウケる], [る], [to be well-received/become popular], [], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [#ruby[手伝][て|つだ]う], [う], [to help/assist/aid; to contribute to], [], [-], [], [], [],
  [#ruby[助][たす]ける], [る], [to save/rescue/spare/help], [], [#ruby[助][たす]かる], [う], [to be saved/rescued/escape harm/survive/helped], [],
  [#ruby[救][すく]う], [う], [to save/rescue from/help out of], [], [-], [], [], [],
  [#ruby[応援][おう|えん]する], [E], [to aid/assist/help/support; to cheer/root for], [], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[感謝][かん|しゃ]する], [E], [to thank], [], [#ruby[感謝][かん|しゃ]する], [E], [to be grateful/thankful], [],
  [#ruby[大感謝][だい|かん|しゃ]する], [E], [to greatly thank], [], [#ruby[大感謝][だい|かん|しゃ]する], [E], [to be greatly grateful/thankful], [],
  [#ruby[評価][ひょう|か]する], [E], [to appreciate/recognise/acknowledge/praise], [also in @tbl:appendix-vocab-verbs-ability], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [？], [], [], [], [(ご)#ruby[注意][ちゅう|い]する], [E], [to pay attention/remind/caution], [],
  [], [], [], [], [#highlight[All WOSURU family]], [], [], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [#ruby[連絡][れん|らく]する], [E], [to make contact/communicate/call/message], [], [-], [], [], [],
  [？], [], [], [], [#ruby[電話][でん|わ]する], [E], [to call (phone call)], [],
  [かける], [る], [to make (a call)], [(#ruby[掛][か]ける)], [かかる], [う], [to get/receive (a call)], [(#ruby[掛][か]かる)],
  [#ruby[電話][でん|わ]をかける], [る], [to telephone/make a call], [(#ruby[電話][でん|わ]を#ruby[掛][か]ける)], [#ruby[電話][でん|わ]がかかる], [う], [to get/receive (a call)], [(#ruby[電話][でん|わ]を#ruby[掛][か]かる)],
  [つなぐ], [う], [to transfer phone call/connect with (に-marked)], [also in @tbl:appendix-vocab-verbs-production], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [#ruby[告白][こく|はく]する], [E], [to confess to a crime/wrongdoing], [#link("https://dictionary.goo.ne.jp/thsrs/10872/meaning/m0u/")[[goo]]], [#ruby[告白][こく|はく]する], [E], [to confess one's romantic feelings], [],
  [#ruby[自白][じ|はく]する], [E], [to confess/admit (when questioned)], [#link("https://dictionary.goo.ne.jp/thsrs/10872/meaning/m0u/")[[goo]]], [-], [], [], [],
  [#ruby[自供][じ|きょう]する], [E], [to confess (when questioned)], [#link("https://dictionary.goo.ne.jp/thsrs/10872/meaning/m0u/")[[goo]]], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[逮捕][たい|ほ]する], [E], [to arrest/capture], [], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [ノートする], [E], [to note down], [], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [], [], [], [], [#ruby[粘][ねば]る], [う], [to be sticky/adhesive], [],
  // [], [], [], [], [], [], [], [],
)


== Health

// @typstyle off
#verb_table(
  [Verbs: health.], // caption
  "tbl:appendix-vocab-verbs-health", // label
  [-], [], [], [], [#ruby[空][す]く], [う], [to be hungry], [also in @tbl:appendix-vocab-verbs-production],
  [-], [], [], [], [#ruby[渇][かわ]く], [う], [to be thirsty; to thirst/crave for (〜に#ruby[渇][かわ]いた)], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [#ruby[汗][あせ]をかく], [う], [to perspire/sweat], [(#ruby[汗][あせ]を#ruby[掻][か]く)], [-], [], [], [],
  [-], [], [], [], [#ruby[疲][つか]れる], [る], [to become tired/fatigued/exhausted (physical/mental); to become worn out (object overuse)], [#link("https://dictionary.goo.ne.jp/thsrs/1411/meaning/m0u/%E7%96%B2%E3%82%8C%E3%82%8B/")[[goo]]],
  [-], [], [], [], [#ruby[疲労][ひ|ろう]する], [E], [to be fatigued/exhausted/tired], [],
  [-], [], [], [], [くたびれる], [る], [to become tired/exhausted/weary (physical); to become worn out (object overuse)], [(#rruby[草臥][くたび]れる); #link("https://dictionary.goo.ne.jp/thsrs/1411/meaning/m0u/%E7%96%B2%E3%82%8C%E3%82%8B/")[[goo]]],
  [-], [], [], [], [バテる], [る], [to be exhausted], [slang],
  [-], [], [], [], [#ruby[病気][びょう|き]になる], [う], [to fall ill/sick], [],
  [かく], [う], [to scratch (e.g. mosquito bite); to perspire], [(#ruby[掻][か]く)], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [-], [], [], [], [#ruby[寝][ね]る], [る], [to lie down/go to bed/sleep], [also in @tbl:appendix-vocab-verbs-consumption; #link("https://dictionary.goo.ne.jp/thsrs/1422/meaning/m0u/")[[goo]]],
  [-], [], [], [], [#ruby[睡][ねむ]る], [う], [to sleep; to rest in peace (euphemism)], [also in @tbl:appendix-vocab-verbs-consumption; #link("https://dictionary.goo.ne.jp/thsrs/1422/meaning/m0u/")[[goo]]],
  [], [], [], [], [#ruby[休][やす]む], [う], [to take a day off/be absent; to rest/have a break], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [#ruby[傷][きず]つける], [る], [to wound/injure/hurt someone's feelings], [(#ruby[傷][きず]#ruby[付][つ]ける)], [#ruby[傷][きず]つく], [う], [to be wounded/get injured/get hurt feelings], [(#ruby[傷][きず]#ruby[付][つ]く)],
  [#ruby[痛][いた]める], [る], [to hurt/injure/cause pain], [], [#ruby[痛][いた]む], [う], [to hurt/ache/feel a pain], [],
  [#ruby[傷][いた]める], [る], [to harm/damage; to spoil], [], [#ruby[傷][いた]む], [う], [to be injured/damaged; to be spoiled (food)], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [#ruby[生][う]む], [う], [to give birth/bear (a child)/lay (eggs); to produce/yield (e.g. interest/returns)], [], [#ruby[生][う]まれる], [る], [to be born], [],
  [#ruby[生][い]かす？], [], [], [], [#ruby[生][い]きる], [る], [to live/come to life/make a living], [],
  [#ruby[生][しょう]じる], [＊], [a lot!], [], [], [], [], [],
  [#ruby[生][う]み#ruby[出][だ]す], [＊], [a lot!], [], [], [], [], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [], [], [], [], [#ruby[死][し]ぬ], [う], [to die/pass away], [],
  // [], [], [], [], [], [], [], [],
)


== Ability

// @typstyle off
#verb_table(
  [Verbs: ability.], // caption
  "tbl:appendix-vocab-verbs-ability", // label
  [-], [], [], [], [あり#ruby[得][え]る], [る], [to be possible/conceivable/likely/probable], [],
  [-], [], [], [], [できる], [る], [to be able to do], [(#ruby[出来][で|き]る); also in @tbl:appendix-vocab-verbs-interaction],
  [#ruby[料理][りょう|り]する], [E], [to deal with skilfully/handle well], [], [-], [], [], [],
  [-], [], [], [], [イケる], [る], [to look/taste good; to be good at (esp. food); to go well], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [-], [], [], [], [#ruby[独立][どく|りつ]する], [E], [to be independent/self-reliant], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [-], [], [], [], [#ruby[苦労][く|ろう]する], [E], [to have trouble/difficulty], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[評価][ひょう|か]する], [E], [to rate/appraise/evaluate/assess], [also in @tbl:appendix-vocab-verbs-interaction], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [-], [], [], [], [#ruby[成功][せい|こう]する], [E], [to succeed], [],
  [-], [], [], [], [#ruby[失敗][しっ|ぱい]する], [E], [to fail], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [-], [], [], [], [#ruby[受][う]かる], [う], [to pass an exam], [],
  // [], [], [], [], [], [], [], [],
)


== Education and correctness
#highlight[#link("https://japanese.stackexchange.com/questions/56962/standard-mathematical-operations-expressed-in-japanese")[MATH]]

// @typstyle off
#verb_table(
  [Verbs: education and correctness.], // caption
  "tbl:appendix-vocab-verbs-education-and-correctness", // label
  [#ruby[訊][き]く], [う], [to ask/enquire], [], [？], [], [], [],
  [#ruby[質問][しつ|もん]する], [E], [to ask a question], [], [#ruby[質問][しつ|もん]\[を\]する], [E], [to ask a question], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [#ruby[教][おし]える], [る], [to teach/inform], [], [-], [], [], [],
  [#ruby[教][おそ]わる], [う], [to be taught/learn/take lessons in], [], [-], [], [], [],
  [#ruby[説明][せつ|めい]する], [E], [to explain/describe], [], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[習][なら]う], [う], [to take lessons/learn/be trained (under a teacher)], [], [-], [], [], [],
  [#ruby[練習][れん|しゅう]する], [E], [to practise/train/drill], [], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[勉強][べん|きょう]する], [E], [to study], [], [#ruby[勉強][べん|きょう]する], [E], [to work hard], [],
  [#ruby[自習][じ|しゅう]する], [E], [to self-study], [], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [-], [], [], [], [#ruby[頑張][がん|ば]る], [う], [to persevere/keep at it/hang on/do one's best], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [], [], [], [], [わかる], [う], [to understand/comprehend], [also an interjection],
  [#ruby[了解][りょう|かい]する], [E], [to understand/agree], [], [-], [], [], [],
  [#ruby[理解][り|かい]する], [E], [to understand], [also in @tbl:appendix-vocab-verbs-emotions], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [#ruby[違][ちが]える], [る], [to make a mistake], [#link("https://ja.hinative.com/questions/10453376")[[HN]]], [#ruby[違][ちが]う], [う], [to differ/be different; to be wrong/mistaken], [],
  [#ruby[間違][ま|ちが]える], [る], [to make a mistake in/commit an error/do incorrectly], [], [#ruby[間違][ま|ちが]う], [う], [to be mistaken/incorrect/wrong (oft. as past/progressive)], [],
  [-], [], [], [], [#ruby[異][こと]なる], [う], [to differ/disagree/vary/diverge (of opinions)], [],
  [#ruby[誤解][ご|かい]する], [E], [to have a misunderstanding about], [], [#ruby[誤解][ご|かい]する], [E], [to have a misunderstanding], [#link("https://dictionary.goo.ne.jp/thsrs/3333/meaning/m0u/")[[goo]]],
  [-], [], [], [], [#ruby[勘違][かん|ちが]いする], [E], [to erroneously assume/live in an illusion/be mistaken], [#link("https://dictionary.goo.ne.jp/thsrs/3333/meaning/m0u/")[[goo]]],
  [-], [], [], [], [#ruby[思][おも]い#ruby[違][ちが]いする], [E], [to be mistaken/have a misconception], [#link("https://dictionary.goo.ne.jp/thsrs/3333/meaning/m0u/")[[goo]]],
  // [], [], [], [], [], [], [], [],
)


== Knowledge, truth and reality

// @typstyle off
#verb_table(
  [Verbs: knowledge, truth and reality.], // caption
  "tbl:appendix-vocab-verbs-knowledge-truth-and-reality", // label
  [#ruby[思][おも]う], [う], [to think/believe/judge/imagine/recall/feel], [], [-], [], [], [],
  [#ruby[考][かん]える], [る], [to consider/think over/reflect on], [], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [#ruby[承知][しょう|ち]する], [E], [to know/be aware; to accept/consent/comply/acknowledge], [], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [#ruby[信][しん]じる], [る], [to believe/trust/have faith in], [], [-], [], [], [],
  [#ruby[信用][しん|よう]する], [E], [to trust (information/source; past)], [#link("https://japanese.stackexchange.com/q/24275")[[SE]]], [-], [], [], [],
  [#ruby[信頼][しん|らい]する], [E], [to trust (a person/organisation; future)], [#link("https://japanese.stackexchange.com/q/24275")[[SE]]], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[疑][うたが]う], [う], [to doubt/distrust/be suspicious of], [], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [-], [], [], [], [はっきりする], [E], [to clear (e.g. fog/confusion); to be clear/definite (sight/knowledge)], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[隠][かく]す], [う], [to hide/conceal], [], [#ruby[隠][かく]れる], [る], [to hide/conceal oneself/take cover; to be hidden by/disappear behind; to be unknown/undiscovered], [],
  [#ruby[隠][かく]し#ruby[事][ごと]する], [E], [to keep a secret], [], [-], [], [], [],
  [#ruby[伏][ふ]せる], [る], [to conceal (secret)/place in hiding (in ambush)], [also in @tbl:appendix-vocab-verbs-physical], [-], [], [], [],
  [#ruby[隠蔽][いん|ぺい]する], [E], [to cover up/conceal/hide/suppress], [], [-], [], [], [],
  [-], [], [], [], [なくなる], [う], [to be lost/missing], [(#ruby[無][な]くなる); also in @tbl:appendix-vocab-verbs-consumption],
  // [], [], [], [], [], [], [], [],
  hline,
  [-], [], [], [], [#ruby[気][き]づく], [う], [to notice/realise/sense (internal/somehow nuance)], [(#ruby[気付][き|づ]く); #link("https://ja.hinative.com/questions/23322375")[[HN]]],
  [-], [], [], [], [#ruby[気][き]がつく], [う], [to notice/realise/sense; regain consciousness], [(#ruby[気][き]が#ruby[付][つ]く); #link("https://ja.hinative.com/questions/23322375")[[HN]]],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[知][し]る], [#exception[う]], [to know/be familiar with; to be concerned with (usu.\ negative)], [], [#ruby[知][し]れる], [る], [to be known/understood/discovered], [],
  [#ruby[覚][おぼ]える], [る], [to remember/memorise/learn by heart], [], [-], [], [], [],
  [#ruby[思][おも]い#ruby[出][だ]す], [う], [to recall/remember/recollect], [], [-], [], [], [],
  [#ruby[意識][い|しき]する], [E], [to become aware of], [], [], [], [], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[忘][わす]れる], [る], [to forget], [], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [-], [], [], [], [#ruby[由来][ゆ|らい]する], [E], [to originate from (に-marked)], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[調][しら]べる], [る], [to look up/search/investigate/examine], [], [-], [], [], [],
  [#ruby[観察][かん|さつ]する], [E], [to observe/survey/watch], [], [-], [], [], [],
  [#ruby[探][さが]す], [う], [to search/look/hunt for (something desired)], [], [-], [], [], [],
  [#ruby[捜][さが]す], [う], [to search/look/hunt for (something lost)], [], [-], [], [], [],
  [#ruby[探索][たん|さく]する], [E], [to hunt/explore/investigate/search/lookup], [], [-], [], [], [],
  [#ruby[分析][ぶん|せき]する], [E], [to analyse], [], [-], [], [], [],
  [#ruby[推][お]す], [う], [to infer/deduce/gather/conjecture/surmise from], [also in @tbl:appendix-vocab-verbs-conflict-and-resolution], [-], [], [], [],
  [#ruby[報告][ほう|こく]する], [E], [to report (information)], [], [-], [], [], [],
  [#ruby[証明][しょう|めい]する], [E], [to prove/testify], [], [-], [], [], [],
  [#ruby[確認][かく|にん]する], [E], [to confirm/verify/validate/check], [], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[発見][はっ|けん]する], [E], [to discover/detect/find], [], [-], [], [], [],
  [#ruby[発明][はつ|めい]する], [E], [to invent], [], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[決断][けつ|だん]する], [E], [to decide (strong)], [#link("https://dictionary.goo.ne.jp/thsrs/3217/meaning/m0u/")[[goo]]], [-], [], [], [],
  [#ruby[決定][けっ|てい]する], [E], [to decide], [#link("https://dictionary.goo.ne.jp/thsrs/3217/meaning/m0u/")[[goo]]], [-], [], [], [],
  [#ruby[判断][はん|だん]する], [E], [to judge], [#link("https://dictionary.goo.ne.jp/thsrs/3217/meaning/m0u/")[[goo]]], [-], [], [], [],
  [#ruby[判定][はん|てい]する], [E], [to make a verdict/ruling (of judges/referees)], [#link("https://dictionary.goo.ne.jp/thsrs/3217/meaning/m0u/")[[goo]]], [-], [], [], [],
  [#ruby[断定][だん|てい]する], [E], [to assert/declare/conclude], [#link("https://dictionary.goo.ne.jp/thsrs/3217/meaning/m0u/")[[goo]]], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[内定][ない|てい]する], [E], [to unofficially decide/offer (e.g. job)], [], [#ruby[内定][ない|てい]する], [E], [to unofficially decide/offer (e.g. job)], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[探][さぐ]る], [う], [to feel around/grope/search/find for; to investigate/probe/spy/sound out; to explore (parts unknown)], [], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
)


== Courtesy

// @typstyle off
#verb_table(
  [Verbs: courtesy.], // caption
  "tbl:appendix-vocab-verbs-courtesy", // label
  [#ruby[無視][む|し]する], [E], [to disregard/ignore], [], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  // [], [], [], [], [], [], [], [],
  [-], [], [], [], [#ruby[間][ま]に#ruby[合][あ]う], [う], [to be/make it in time for], [also in @tbl:appendix-vocab-verbs-interaction],
  [#ruby[遅][おく]らす], [う], [to delay/postpone/slow down/retard], [], [#ruby[遅][おく]れる], [る], [to be late/delayed/overdue/slow], [],
  [-], [], [], [], [#ruby[後][おく]れる], [る], [to fall behind others (race/studies)], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[進][すす]める], [る], [to set a clock forwards in time], [also in @tbl:appendix-vocab-verbs-directions], [#ruby[進][すす]む], [う], [to be fast (of a clock)], [also in @tbl:appendix-vocab-verbs-directions],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [かける], [る], [to cause/burden/impose (inconvenience/trouble)], [(#ruby[掛][か]ける)], [-], [], [], [],
  [#ruby[迷惑][めい|わく]をかける], [る], [to annoy/inconvenience/trouble/cause trouble], [(#ruby[迷惑][めい|わく]を#ruby[掛][か]ける)], [-], [], [], [],
  [#ruby[面倒][めん|どう]をかける], [る], [to inconvenience/trouble], [(#ruby[面倒][めん|どう]を#ruby[掛][か]ける)], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
)


== Conflict and resolution

// @typstyle off
#verb_table(
  [Verbs: conflict and resolution.], // caption
  "tbl:appendix-vocab-verbs-conflict-and-resolution", // label
  [-], [], [], [], [#ruby[争][あらそ]う], [to compete/contest/contend], [], [],
  [-], [], [], [], [#ruby[勝][か]つ], [う], [to win (personal)], [],
  [-], [], [], [], [#ruby[勝利][しょう|り]する], [E], [to win (larger scale)], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[攻][せ]める], [る], [to attack/assault/assail], [], [-], [], [], [],
  [-], [], [], [], [#ruby[抗][あらが]う], [う], [to fight against/resist/oppose], [],
  [#ruby[倒][たお]す], [う], [to kill/defeat/beat/overthrow], [also in @tbl:appendix-vocab-verbs-directions], [#ruby[倒][たお]れる], [る], [to be killed (person)/fall (organisation)], [also in @tbl:appendix-vocab-verbs-directions; #link("https://ja.hinative.com/questions/22550436")[[HN]]],
  [#ruby[負][ま]かす], [う], [to defeat], [#link("https://ja.hinative.com/questions/15696906")[[HN]]], [#ruby[負][ま]ける], [る], [to lose (personal)/succumb to/give in to], [],
  [#ruby[敗][やぶ]る], [う], [to defeat/beat], [#link("https://ja.hinative.com/questions/15696906")[[HN]]], [#ruby[敗][やぶ]れる], [る], [to lose/be defeated/beaten/unsuccessful], [],
  [-], [], [], [], [#ruby[敗北][はい|ぼく]する], [E], [to lose (larger scale)], [],
  [#ruby[食][く]う], [う], [to outdo/defeat], [also in @tbl:appendix-vocab-verbs-consumption], [-], [], [], [],
  [#ruby[全滅][ぜん|めつ]する], [E], [to completely destroy/annihilate/wipe out], [], [#ruby[全滅][ぜん|めつ]する], [E], [to be totally defeated/completely fail], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [#ruby[騙][だま]す], [う], [to trick/cheat/deceive], [], [-], [], [], [],
  [#ruby[馬鹿][ば|か]にする], [E], [to make fun of/look down on/make light of], [], [-], [], [], [],
  [#ruby[後出][あと|だ]しする], [E], [to wait to see one's opponent's move before making your move (disallowed in games); to hold back until the last minute], [], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[誤][あやま]る], [う], [to err/make a mistake in; to mislead/misguide/lead astray], [], [#ruby[誤][あやま]る], [う], [to be mistaken/wrong/incorrect], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [-], [], [], [], [#ruby[喧嘩][けん|か]する], [E], [to quarrel/brawl/fight/squabble/scuffle/argue], [],
  [#ruby[脅][おど]す], [う], [to threaten/menace], [#link("https://dictionary.goo.ne.jp/thsrs/9381/meaning/m0u/")[[goo]]], [-], [], [], [],
  [#ruby[脅][おど]かす], [う], [to threaten/menace], [#link("https://dictionary.goo.ne.jp/thsrs/9381/meaning/m0u/")[[goo]]; also in @tbl:appendix-vocab-verbs-emotions], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[責][せ]める], [る], [to blame/condemn/critise/reproach], [], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[謝][あやま]る], [う], [to apologise], [], [-], [], [], [],
  [#ruby[謝罪][しゃ|ざい]する], [E], [to apologise], [], [-], [], [], [],
  [#ruby[勘弁][かん|べん]する], [E], [to pardon/forgive; to give someone a break], [], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[許][ゆる]す], [う], [to allow/approve; forgive/excuse], [], [-], [], [], [],
  [-], [], [], [], [#ruby[構][かま]う], [う], [to mind/care about/be concerned about/have a regard for (に-marked)], [],
  [#ruby[気][き]にする], [E], [(negative nuance) to mind/care/worry about something], [], [#ruby[気][き]にする], [E], [(negative nuance) to mind/care/worry about something], [],
  [-], [], [], [], [#ruby[賛成][さん|せい]する], [E], [to approve of/agree with/support (に-marked)], [],
  [#ruby[推][お]す], [う], [to recommend/endorse/nominate/support/back], [also in @tbl:appendix-vocab-verbs-knowledge-truth-and-reality], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[否][いな]む], [う], [to refuse/decline], [], [-], [], [], [],
  [-], [], [], [], [お#ruby[断][ことわ]りします], [E], [I decline/refuse/reject/do not accept], [polite],
  // [], [], [], [], [], [], [], [],
  hline,
  [-], [], [], [], [#ruby[気][き]をつける], [る], [to be careful of/pay attention to/take care of (に-marked)], [(#ruby[気][き]を#ruby[付][つ]ける)],
  [#ruby[警戒][けい|かい]する], [E], [to be cautious of/be on guard against], [], [-], [], [], [],
  [-], [], [], [], [#ruby[反対][はん|たい]する], [E], [to object/oppose/disagree with/resist (に-marked)], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[禁][きん]じる/#ruby[禁][きん]ず[る]], [る], [to forbid/ban/prohibit], [#highlight[some zuru verb black magic]], [-], [], [], [],
  [ブロックする], [E], [to block (user/website); to obstruct], [], [-], [], [], [],
  [バンする], [E], [to ban (an online account)], [slang], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[約束][やく|そく]する], [E], [to promise/make an agreement], [], [-], [], [], [],
  [#ruby[守][まも]る], [う], [to keep/uphold/abide by/follow (promise/rules)], [also in @tbl:appendix-vocab-verbs-production], [-], [], [], [],
  [#ruby[破][やぶ]る], [う], [to break/violate (silence/promise/rules)], [also in @tbl:appendix-vocab-verbs-production], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [#ruby[捕][つか]まえる], [る], [to arrest/catch/capture/seize/restrain], [], [#ruby[捕][つか]まる], [う], [to be caught/arrested], [],
  [#ruby[尋問][じん|もん]する], [E], [to interrogate/question], [], [-], [], [], [],
  [#ruby[罰][ばっ]する], [E], [to punish/penalise], [], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [#ruby[殺][ころ]す], [う], [to kill; to suppress/destroy/stifle (talent/feelings/yawn/laugh)], [], [-], [], [], [],
  [ぶち#ruby[殺][ころ]す], [う], [to beat to death; to kill (emphatic)], [], [-], [], [], [],
  [-], [], [], [], [#ruby[自殺][じ|さつ]する], [E], [to suicide], [],
  // [], [], [], [], [], [], [], [],
)


== Change

// @typstyle off
#verb_table(
  [Verbs: change.], // caption
  "tbl:appendix-vocab-verbs-change", // label
  [-], [], [], [], [#ruby[変化][へん|か]する], [E], [to change/vary/mutate/transition/transform/be altered/transfigured; inflect/conjugate (grammar)], [],
  [-], [], [], [], [#ruby[進化][しん|か]する], [E], [to evolve/advance/progress/develop/improve], [],
  [#ruby[展開][てん|かい]する], [E], [to develop/evolve/progress/unfold/plot twist; to expand (physical/mathematical)], [], [#ruby[展開][てん|かい]する], [E], [to develop/evolve/progress/unfold/plot twist; to expand (physical/mathematical)], [],
  // [], [], [], [], [], [], [], [],
  hline,
  [#ruby[変][か]える], [る], [to alter/transform/convert/vary/change], [], [#ruby[変][か]わる], [う], [to transform/change; to move to (new place)], [],
  [#ruby[換][か]える], [る], [to exchange], [], [#ruby[換][か]わる], [る], [to switch/be exchanged/change places], [],
  [#ruby[替][か]える], [る], [to replace], [], [#ruby[替][か]わる], [る], [to relieve/replace], [],
  [#ruby[代][か]える], [る], [to substitute], [], [#ruby[代][か]わる], [る], [to substitute/hand over (telephone)], [],
  hline,
  [#ruby[切][き]り#ruby[変][か]える], [る], [to alter/transform/convert/vary/change], [], [-], [], [], [],
  [#ruby[切][き]り#ruby[替][か]える], [る], [to replace], [], [-], [], [], [],
  [#ruby[切][き]り#ruby[換][か]える], [る], [to exchange], [], [-], [], [], [],
  [#ruby[取][と]り#ruby[替][か]える], [る], [to replace (widest usage; "take and replace")], [#link("https://dictionary.goo.ne.jp/thsrs/16443/meaning/m0u/")[[goo]]], [-], [], [], [],
  [#ruby[入][い]れ#ruby[替][か]える], [る], [to replace (only interior contents; "enter and replace")], [#link("https://dictionary.goo.ne.jp/thsrs/16443/meaning/m0u/")[[goo]]], [-], [], [], [],
  [#ruby[付][つ]け#ruby[替][か]える], [る], [to replace (can replace to different location; "(re)attach and replace")], [#link("https://dictionary.goo.ne.jp/thsrs/16443/meaning/m0u/")[[goo]]], [-], [], [], [],
  [#ruby[入][い]れ#ruby[換][か]える], [る], [to exchange], [], [-], [], [], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [-], [], [], [], [#ruby[声変][こえ|がわり]する], [E], [to break voice], [],
  [-], [], [], [], [#ruby[痩][や]せる], [る], [to lose weight/become thin; to become impoverished/infertile/barren (soil)], [],
  [-], [], [], [], [#ruby[太][ふと]る], [う], [to put on weight/grow fat], [],
  [-], [], [], [], [#ruby[禿][は]げる], [る], [to lose hair/become bald], [],
  // [], [], [], [], [], [], [], [],
  thickhline,
  [-], [], [], [], [#ruby[紅葉][こう|よう]する], [E], [to turn red (of leaves, in autumn)], [],
  [-], [], [], [], [#ruby[黄葉][こう|よう]する], [E], [to turn yellow (of leaves, in autumn)], [],
  // [], [], [], [], [], [], [], [],
)

#highlight[SUFFIXES AND AUXES]

