services:
  frontend:
    build:
      context: frontend
    ports:
      - 80:80

  backend:
    build:
      context: backend
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ../typst
        target: /nihongo/typst
        read_only: true
    working_dir: /nihongo/dev-server/backend
    command: app --diff-strategy sync /nihongo/typst/nihongo-gakushuu-kyouzai.pdf
